// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delivery_attempts.sql

package timeseries

import (
	"context"
	"time"
)

const insertDeliveryAttempt = `-- name: InsertDeliveryAttempt :exec

INSERT INTO delivery_attempts (
    at, delivery_id, subscription_id, change_id, attempt, status_code, error,
    latency_ms, payload_bytes, deliver_instance
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertDeliveryAttemptParams struct {
	At              time.Time
	DeliveryID      string
	SubscriptionID  string
	ChangeID        int64
	Attempt         int32
	StatusCode      *int32
	Error           *string
	LatencyMs       int32
	PayloadBytes    int32
	DeliverInstance string
}

// WP-1: the delivery log (written by deliver only, WP-6).
func (q *Queries) InsertDeliveryAttempt(ctx context.Context, arg InsertDeliveryAttemptParams) error {
	_, err := q.db.Exec(ctx, insertDeliveryAttempt,
		arg.At,
		arg.DeliveryID,
		arg.SubscriptionID,
		arg.ChangeID,
		arg.Attempt,
		arg.StatusCode,
		arg.Error,
		arg.LatencyMs,
		arg.PayloadBytes,
		arg.DeliverInstance,
	)
	return err
}

const listDeliveryAttempts = `-- name: ListDeliveryAttempts :many
SELECT at, delivery_id, subscription_id, change_id, attempt, status_code, error,
       latency_ms, payload_bytes, deliver_instance
FROM delivery_attempts
WHERE subscription_id = $1 AND at < $2
ORDER BY at DESC
LIMIT $3
`

type ListDeliveryAttemptsParams struct {
	SubscriptionID string
	Before         time.Time
	MaxRows        int32
}

func (q *Queries) ListDeliveryAttempts(ctx context.Context, arg ListDeliveryAttemptsParams) ([]DeliveryAttempt, error) {
	rows, err := q.db.Query(ctx, listDeliveryAttempts, arg.SubscriptionID, arg.Before, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeliveryAttempt
	for rows.Next() {
		var i DeliveryAttempt
		if err := rows.Scan(
			&i.At,
			&i.DeliveryID,
			&i.SubscriptionID,
			&i.ChangeID,
			&i.Attempt,
			&i.StatusCode,
			&i.Error,
			&i.LatencyMs,
			&i.PayloadBytes,
			&i.DeliverInstance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
