// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package timeseries

import (
	"time"
)

type DeliveryAttempt struct {
	At              time.Time
	DeliveryID      string
	SubscriptionID  string
	ChangeID        int64
	Attempt         int32
	StatusCode      *int32
	Error           *string
	LatencyMs       int32
	PayloadBytes    int32
	DeliverInstance string
}
