// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: console.sql

package relational

import (
	"context"
	"time"
)

const consoleNow = `-- name: ConsoleNow :one

SELECT now()::timestamptz AS now
`

// WP-8: console accounts, sessions, the console's read models and its
// audited actions (docs/PLAN.md section 6.6). Nothing here writes
// publications, features, features_current, snapshots or restrictions.
// The database's clock: lockouts, session expiry and TOTP steps are
// judged on it, never on a replica's clock.
func (q *Queries) ConsoleNow(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, consoleNow)
	var now time.Time
	err := row.Scan(&now)
	return now, err
}

const consoleResumeSubscription = `-- name: ConsoleResumeSubscription :exec
UPDATE subscriptions SET status = 'pending_verification', suspended_reason = NULL,
    consecutive_failures = 0, failing_since = NULL
WHERE id = $1
`

// Back to pending_verification with a new ping (WP-6: a suspended
// subscription is verified again before it receives).
func (q *Queries) ConsoleResumeSubscription(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, consoleResumeSubscription, id)
	return err
}

const consoleSuspendSubscription = `-- name: ConsoleSuspendSubscription :exec
UPDATE subscriptions SET status = 'suspended', suspended_reason = $1 WHERE id = $2
`

type ConsoleSuspendSubscriptionParams struct {
	Reason *string
	ID     string
}

func (q *Queries) ConsoleSuspendSubscription(ctx context.Context, arg ConsoleSuspendSubscriptionParams) error {
	_, err := q.db.Exec(ctx, consoleSuspendSubscription, arg.Reason, arg.ID)
	return err
}

const countLoginChallengeAttempt = `-- name: CountLoginChallengeAttempt :exec
UPDATE login_challenges SET attempts = attempts + 1 WHERE token_hash = $1
`

func (q *Queries) CountLoginChallengeAttempt(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, countLoginChallengeAttempt, tokenHash)
	return err
}

const deleteSpentLoginChallenges = `-- name: DeleteSpentLoginChallenges :execrows
DELETE FROM login_challenges
WHERE account_id = $1 AND (used_at IS NOT NULL OR expires_at <= $2)
`

type DeleteSpentLoginChallengesParams struct {
	AccountID string
	Now       time.Time
}

// Before a new challenge: the account's used and expired ones go (E-10).
func (q *Queries) DeleteSpentLoginChallenges(ctx context.Context, arg DeleteSpentLoginChallengesParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSpentLoginChallenges, arg.AccountID, arg.Now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deliverySummaries = `-- name: DeliverySummaries :many
SELECT subscription_id, state, count(*)::bigint AS n
FROM deliveries
WHERE subscription_id = ANY($1::text[])
GROUP BY subscription_id, state
`

type DeliverySummariesRow struct {
	SubscriptionID string
	State          string
	N              int64
}

// Per subscription and state, the number of deliveries.
func (q *Queries) DeliverySummaries(ctx context.Context, ids []string) ([]DeliverySummariesRow, error) {
	rows, err := q.db.Query(ctx, deliverySummaries, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeliverySummariesRow
	for rows.Next() {
		var i DeliverySummariesRow
		if err := rows.Scan(&i.SubscriptionID, &i.State, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventHashBefore = `-- name: EventHashBefore :one
SELECT hash FROM events WHERE id < $1 ORDER BY id DESC LIMIT 1
`

// The hash of the row just before id in the chain.
func (q *Queries) EventHashBefore(ctx context.Context, id int64) ([]byte, error) {
	row := q.db.QueryRow(ctx, eventHashBefore, id)
	var hash []byte
	err := row.Scan(&hash)
	return hash, err
}

const eventIDBounds = `-- name: EventIDBounds :one
SELECT COALESCE(min(id), 0)::bigint AS first_id, COALESCE(max(id), 0)::bigint AS last_id
FROM events
WHERE ts >= $1 AND ts < $2
`

type EventIDBoundsParams struct {
	FromTs time.Time
	ToTs   time.Time
}

type EventIDBoundsRow struct {
	FirstID int64
	LastID  int64
}

// The first and last id of the rows in [from, to): the chain is by id.
func (q *Queries) EventIDBounds(ctx context.Context, arg EventIDBoundsParams) (EventIDBoundsRow, error) {
	row := q.db.QueryRow(ctx, eventIDBounds, arg.FromTs, arg.ToTs)
	var i EventIDBoundsRow
	err := row.Scan(&i.FirstID, &i.LastID)
	return i, err
}

const getAccount = `-- name: GetAccount :one
SELECT id, username, password_hash, role, totp_secret_enc, mfa_required, status, created_at,
       last_login_at, failed_logins, locked_until, totp_last_step
FROM accounts
WHERE id = $1
`

func (q *Queries) GetAccount(ctx context.Context, id string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.TotpSecretEnc,
		&i.MfaRequired,
		&i.Status,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.FailedLogins,
		&i.LockedUntil,
		&i.TotpLastStep,
	)
	return i, err
}

const getAccountByUsernameForUpdate = `-- name: GetAccountByUsernameForUpdate :one
SELECT id, username, password_hash, role, totp_secret_enc, mfa_required, status, created_at,
       last_login_at, failed_logins, locked_until, totp_last_step
FROM accounts
WHERE username = $1
FOR UPDATE
`

// The login's row lock: the failed-login counter, the lockout and the
// TOTP replay step are read and written under it.
func (q *Queries) GetAccountByUsernameForUpdate(ctx context.Context, username string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByUsernameForUpdate, username)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.TotpSecretEnc,
		&i.MfaRequired,
		&i.Status,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.FailedLogins,
		&i.LockedUntil,
		&i.TotpLastStep,
	)
	return i, err
}

const getAccountForUpdate = `-- name: GetAccountForUpdate :one
SELECT id, username, password_hash, role, totp_secret_enc, mfa_required, status, created_at,
       last_login_at, failed_logins, locked_until, totp_last_step
FROM accounts
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetAccountForUpdate(ctx context.Context, id string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountForUpdate, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.TotpSecretEnc,
		&i.MfaRequired,
		&i.Status,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.FailedLogins,
		&i.LockedUntil,
		&i.TotpLastStep,
	)
	return i, err
}

const getLoginChallenge = `-- name: GetLoginChallenge :one
SELECT token_hash, account_id, created_at, expires_at, attempts, used_at FROM login_challenges WHERE token_hash = $1
`

// The account a challenge is bound to, read before the account's row
// lock: the lock order is the account, then the challenge, as the
// password step takes them.
func (q *Queries) GetLoginChallenge(ctx context.Context, tokenHash string) (LoginChallenge, error) {
	row := q.db.QueryRow(ctx, getLoginChallenge, tokenHash)
	var i LoginChallenge
	err := row.Scan(
		&i.TokenHash,
		&i.AccountID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Attempts,
		&i.UsedAt,
	)
	return i, err
}

const getLoginChallengeForUpdate = `-- name: GetLoginChallengeForUpdate :one
SELECT token_hash, account_id, created_at, expires_at, attempts, used_at FROM login_challenges WHERE token_hash = $1 FOR UPDATE
`

func (q *Queries) GetLoginChallengeForUpdate(ctx context.Context, tokenHash string) (LoginChallenge, error) {
	row := q.db.QueryRow(ctx, getLoginChallengeForUpdate, tokenHash)
	var i LoginChallenge
	err := row.Scan(
		&i.TokenHash,
		&i.AccountID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Attempts,
		&i.UsedAt,
	)
	return i, err
}

const getPublicationByID = `-- name: GetPublicationByID :one
SELECT id, dataset, version, publisher_client_id, received_at, body, feature_count, added,
       changed, removed, supersedes_version, reason
FROM publications
WHERE id = $1
`

type GetPublicationByIDRow struct {
	ID                string
	Dataset           string
	Version           int64
	PublisherClientID string
	ReceivedAt        time.Time
	Body              []byte
	FeatureCount      int32
	Added             int32
	Changed           int32
	Removed           int32
	SupersedesVersion *int64
	Reason            string
}

func (q *Queries) GetPublicationByID(ctx context.Context, id string) (GetPublicationByIDRow, error) {
	row := q.db.QueryRow(ctx, getPublicationByID, id)
	var i GetPublicationByIDRow
	err := row.Scan(
		&i.ID,
		&i.Dataset,
		&i.Version,
		&i.PublisherClientID,
		&i.ReceivedAt,
		&i.Body,
		&i.FeatureCount,
		&i.Added,
		&i.Changed,
		&i.Removed,
		&i.SupersedesVersion,
		&i.Reason,
	)
	return i, err
}

const getPublicationIDByVersion = `-- name: GetPublicationIDByVersion :one
SELECT id FROM publications WHERE dataset = $1 AND version = $2
`

type GetPublicationIDByVersionParams struct {
	Dataset string
	Version int64
}

func (q *Queries) GetPublicationIDByVersion(ctx context.Context, arg GetPublicationIDByVersionParams) (string, error) {
	row := q.db.QueryRow(ctx, getPublicationIDByVersion, arg.Dataset, arg.Version)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getSession = `-- name: GetSession :one
SELECT jti, account_id, issued_at, expires_at, revoked_at, last_seen_at FROM sessions WHERE jti = $1
`

func (q *Queries) GetSession(ctx context.Context, jti string) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, jti)
	var i Session
	err := row.Scan(
		&i.Jti,
		&i.AccountID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getSubscriptionStatusForUpdate = `-- name: GetSubscriptionStatusForUpdate :one
SELECT status FROM subscriptions WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetSubscriptionStatusForUpdate(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getSubscriptionStatusForUpdate, id)
	var status string
	err := row.Scan(&status)
	return status, err
}

const insertAccount = `-- name: InsertAccount :exec
INSERT INTO accounts (id, username, password_hash, role, totp_secret_enc, mfa_required, status, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertAccountParams struct {
	ID            string
	Username      string
	PasswordHash  string
	Role          string
	TotpSecretEnc []byte
	MfaRequired   bool
	Status        string
	CreatedAt     time.Time
}

func (q *Queries) InsertAccount(ctx context.Context, arg InsertAccountParams) error {
	_, err := q.db.Exec(ctx, insertAccount,
		arg.ID,
		arg.Username,
		arg.PasswordHash,
		arg.Role,
		arg.TotpSecretEnc,
		arg.MfaRequired,
		arg.Status,
		arg.CreatedAt,
	)
	return err
}

const insertLoginChallenge = `-- name: InsertLoginChallenge :exec
INSERT INTO login_challenges (token_hash, account_id, created_at, expires_at) VALUES ($1, $2, $3, $4)
`

type InsertLoginChallengeParams struct {
	TokenHash string
	AccountID string
	CreatedAt time.Time
	ExpiresAt time.Time
}

func (q *Queries) InsertLoginChallenge(ctx context.Context, arg InsertLoginChallengeParams) error {
	_, err := q.db.Exec(ctx, insertLoginChallenge,
		arg.TokenHash,
		arg.AccountID,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO sessions (jti, account_id, issued_at, expires_at, last_seen_at) VALUES ($1, $2, $3, $4, $3)
`

type InsertSessionParams struct {
	Jti       string
	AccountID string
	IssuedAt  time.Time
	ExpiresAt time.Time
}

// A new session was last seen when it was issued.
func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.Exec(ctx, insertSession,
		arg.Jti,
		arg.AccountID,
		arg.IssuedAt,
		arg.ExpiresAt,
	)
	return err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, username, password_hash, role, totp_secret_enc, mfa_required, status, created_at,
       last_login_at, failed_logins, locked_until, totp_last_step
FROM accounts
ORDER BY username
LIMIT $1
`

func (q *Queries) ListAccounts(ctx context.Context, maxRows int32) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccounts, maxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.Role,
			&i.TotpSecretEnc,
			&i.MfaRequired,
			&i.Status,
			&i.CreatedAt,
			&i.LastLoginAt,
			&i.FailedLogins,
			&i.LockedUntil,
			&i.TotpLastStep,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllSubscriptions = `-- name: ListAllSubscriptions :many
SELECT id, client_id, callback_url, datasets, status, created_at, verified_at, suspended_reason,
       consecutive_failures, last_success_at, failing_since,
       (bbox IS NOT NULL)::boolean AS has_bbox,
       COALESCE(ST_XMin(bbox), 0)::float8 AS min_lon, COALESCE(ST_YMin(bbox), 0)::float8 AS min_lat,
       COALESCE(ST_XMax(bbox), 0)::float8 AS max_lon, COALESCE(ST_YMax(bbox), 0)::float8 AS max_lat
FROM subscriptions
WHERE id > $1
  AND ($2::boolean OR status <> 'deleted')
  AND ($3::text IS NULL OR status = $3)
ORDER BY id
LIMIT $4
`

type ListAllSubscriptionsParams struct {
	AfterID        string
	IncludeDeleted bool
	Status         *string
	MaxRows        int32
}

type ListAllSubscriptionsRow struct {
	ID                  string
	ClientID            string
	CallbackUrl         string
	Datasets            []string
	Status              string
	CreatedAt           time.Time
	VerifiedAt          *time.Time
	SuspendedReason     *string
	ConsecutiveFailures int32
	LastSuccessAt       *time.Time
	FailingSince        *time.Time
	HasBbox             bool
	MinLon              float64
	MinLat              float64
	MaxLon              float64
	MaxLat              float64
}

// Every client's subscriptions, deleted ones only when asked, oldest
// first, paged by id.
func (q *Queries) ListAllSubscriptions(ctx context.Context, arg ListAllSubscriptionsParams) ([]ListAllSubscriptionsRow, error) {
	rows, err := q.db.Query(ctx, listAllSubscriptions,
		arg.AfterID,
		arg.IncludeDeleted,
		arg.Status,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllSubscriptionsRow
	for rows.Next() {
		var i ListAllSubscriptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.CallbackUrl,
			&i.Datasets,
			&i.Status,
			&i.CreatedAt,
			&i.VerifiedAt,
			&i.SuspendedReason,
			&i.ConsecutiveFailures,
			&i.LastSuccessAt,
			&i.FailingSince,
			&i.HasBbox,
			&i.MinLon,
			&i.MinLat,
			&i.MaxLon,
			&i.MaxLat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT id, ts, actor_type, actor_id, event_type, entity_type, entity_id, payload, prev_hash, hash
FROM events
WHERE id < $1
  AND ts >= $2
  AND ($3::text IS NULL OR actor_id = $3)
  AND ($4::text IS NULL OR event_type = $4)
ORDER BY id DESC
LIMIT $5
`

type ListAuditEventsParams struct {
	BeforeID  int64
	Since     time.Time
	Actor     *string
	EventType *string
	MaxRows   int32
}

// The audit query, newest first, paged by id.
func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listAuditEvents,
		arg.BeforeID,
		arg.Since,
		arg.Actor,
		arg.EventType,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.ActorType,
			&i.ActorID,
			&i.EventType,
			&i.EntityType,
			&i.EntityID,
			&i.Payload,
			&i.PrevHash,
			&i.Hash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChangedFeatures = `-- name: ListChangedFeatures :many
SELECT feature_id, feature, op FROM features
WHERE publication_id = $1 AND op <> 'unchanged'
ORDER BY feature_id
LIMIT $2
`

type ListChangedFeaturesParams struct {
	PublicationID string
	MaxRows       int32
}

type ListChangedFeaturesRow struct {
	FeatureID string
	Feature   []byte
	Op        string
}

// A version's added, changed and removed features (unchanged ones
// left out), at most max_rows.
func (q *Queries) ListChangedFeatures(ctx context.Context, arg ListChangedFeaturesParams) ([]ListChangedFeaturesRow, error) {
	rows, err := q.db.Query(ctx, listChangedFeatures, arg.PublicationID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChangedFeaturesRow
	for rows.Next() {
		var i ListChangedFeaturesRow
		if err := rows.Scan(&i.FeatureID, &i.Feature, &i.Op); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByID = `-- name: ListEventsByID :many
SELECT id, ts, actor_type, actor_id, event_type, entity_type, entity_id, payload, prev_hash, hash
FROM events
WHERE id >= $1 AND id <= $2
ORDER BY id
LIMIT $3
`

type ListEventsByIDParams struct {
	FirstID int64
	LastID  int64
	MaxRows int32
}

// Rows from id first_id up to last_id, in chain order.
func (q *Queries) ListEventsByID(ctx context.Context, arg ListEventsByIDParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsByID, arg.FirstID, arg.LastID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.ActorType,
			&i.ActorID,
			&i.EventType,
			&i.EntityType,
			&i.EntityID,
			&i.Payload,
			&i.PrevHash,
			&i.Hash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeaturesByIDs = `-- name: ListFeaturesByIDs :many
SELECT feature_id, feature FROM features
WHERE publication_id = $1 AND feature_id = ANY($2::text[])
`

type ListFeaturesByIDsParams struct {
	PublicationID string
	Ids           []string
}

type ListFeaturesByIDsRow struct {
	FeatureID string
	Feature   []byte
}

func (q *Queries) ListFeaturesByIDs(ctx context.Context, arg ListFeaturesByIDsParams) ([]ListFeaturesByIDsRow, error) {
	rows, err := q.db.Query(ctx, listFeaturesByIDs, arg.PublicationID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFeaturesByIDsRow
	for rows.Next() {
		var i ListFeaturesByIDsRow
		if err := rows.Scan(&i.FeatureID, &i.Feature); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRevokedSessions = `-- name: ListRevokedSessions :many
SELECT jti FROM sessions
WHERE revoked_at IS NOT NULL AND expires_at > now()
ORDER BY expires_at DESC
LIMIT $1
`

// The revocation list every replica reloads: revoked and not expired.
func (q *Queries) ListRevokedSessions(ctx context.Context, maxRows int32) ([]string, error) {
	rows, err := q.db.Query(ctx, listRevokedSessions, maxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var jti string
		if err := rows.Scan(&jti); err != nil {
			return nil, err
		}
		items = append(items, jti)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockActiveAdmins = `-- name: LockActiveAdmins :many
SELECT id FROM accounts WHERE role = 'admin' AND status = 'active' ORDER BY id FOR UPDATE
`

// The last-admin invariant: every active admin row locked, so two
// demotions at once cannot both see another admin left.
func (q *Queries) LockActiveAdmins(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, lockActiveAdmins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAccountSessions = `-- name: RevokeAccountSessions :many
UPDATE sessions SET revoked_at = now()
WHERE account_id = $1 AND revoked_at IS NULL AND expires_at > now()
RETURNING jti
`

// Every open session of an account (a role change, a disable).
func (q *Queries) RevokeAccountSessions(ctx context.Context, accountID string) ([]string, error) {
	rows, err := q.db.Query(ctx, revokeAccountSessions, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var jti string
		if err := rows.Scan(&jti); err != nil {
			return nil, err
		}
		items = append(items, jti)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSession = `-- name: RevokeSession :execrows
UPDATE sessions SET revoked_at = now() WHERE jti = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, jti string) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSession, jti)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sessionRevoked = `-- name: SessionRevoked :one
SELECT (revoked_at IS NOT NULL OR expires_at <= now())::boolean AS revoked FROM sessions WHERE jti = $1
`

func (q *Queries) SessionRevoked(ctx context.Context, jti string) (bool, error) {
	row := q.db.QueryRow(ctx, sessionRevoked, jti)
	var revoked bool
	err := row.Scan(&revoked)
	return revoked, err
}

const touchSession = `-- name: TouchSession :execrows
UPDATE sessions SET last_seen_at = now()
WHERE jti = $1
  AND revoked_at IS NULL
  AND expires_at > now()
  AND last_seen_at > now() - make_interval(secs => $2::double precision)
`

type TouchSessionParams struct {
	Jti   string
	IdleS float64
}

// A use of a live session moves last_seen_at to now; a session that is
// revoked, expired, idle for more than idle_s or unknown is not touched
// (0 rows), and is over.
func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, touchSession, arg.Jti, arg.IdleS)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAccount = `-- name: UpdateAccount :exec
UPDATE accounts SET
    role = $1,
    status = $2,
    mfa_required = $3,
    totp_secret_enc = $4,
    totp_last_step = $5
WHERE id = $6
`

type UpdateAccountParams struct {
	Role          string
	Status        string
	MfaRequired   bool
	TotpSecretEnc []byte
	TotpLastStep  *int64
	ID            string
}

// An admin's change: role, status and MFA.
func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) error {
	_, err := q.db.Exec(ctx, updateAccount,
		arg.Role,
		arg.Status,
		arg.MfaRequired,
		arg.TotpSecretEnc,
		arg.TotpLastStep,
		arg.ID,
	)
	return err
}

const updateAccountLogin = `-- name: UpdateAccountLogin :exec
UPDATE accounts SET
    failed_logins = $1,
    locked_until = $2,
    last_login_at = $3,
    password_hash = $4,
    totp_last_step = $5
WHERE id = $6
`

type UpdateAccountLoginParams struct {
	FailedLogins int32
	LockedUntil  *time.Time
	LastLoginAt  *time.Time
	PasswordHash string
	TotpLastStep *int64
	ID           string
}

// A login's outcome: the counter, the lockout, the last login, a
// re-hashed password and the last TOTP step.
func (q *Queries) UpdateAccountLogin(ctx context.Context, arg UpdateAccountLoginParams) error {
	_, err := q.db.Exec(ctx, updateAccountLogin,
		arg.FailedLogins,
		arg.LockedUntil,
		arg.LastLoginAt,
		arg.PasswordHash,
		arg.TotpLastStep,
		arg.ID,
	)
	return err
}

const useLoginChallenge = `-- name: UseLoginChallenge :exec
UPDATE login_challenges SET used_at = $1 WHERE token_hash = $2
`

type UseLoginChallengeParams struct {
	UsedAt    *time.Time
	TokenHash string
}

func (q *Queries) UseLoginChallenge(ctx context.Context, arg UseLoginChallengeParams) error {
	_, err := q.db.Exec(ctx, useLoginChallenge, arg.UsedAt, arg.TokenHash)
	return err
}
