// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deliver.sql

package relational

import (
	"context"
	"time"
)

const advanceWatermark = `-- name: AdvanceWatermark :exec
INSERT INTO deliver_state (name, watermark, updated_at)
VALUES ($1, $2, $3)
ON CONFLICT (name) DO UPDATE
SET watermark = GREATEST(deliver_state.watermark, EXCLUDED.watermark), updated_at = EXCLUDED.updated_at
`

type AdvanceWatermarkParams struct {
	Name      string
	Watermark int64
	Now       time.Time
}

// Never moves back: two instances may write it.
func (q *Queries) AdvanceWatermark(ctx context.Context, arg AdvanceWatermarkParams) error {
	_, err := q.db.Exec(ctx, advanceWatermark, arg.Name, arg.Watermark, arg.Now)
	return err
}

const claimDeliveries = `-- name: ClaimDeliveries :many
WITH busy AS (
    SELECT subscription_id, count(*) AS n
    FROM deliveries
    WHERE state = 'delivering' AND next_retry_at > $2::timestamptz
    GROUP BY subscription_id
), ranked AS (
    SELECT d.id, d.next_retry_at,
           row_number() OVER (PARTITION BY d.subscription_id ORDER BY d.next_retry_at, d.id) AS rn,
           COALESCE(b.n, 0) AS busy
    FROM deliveries d
    JOIN subscriptions s ON s.id = d.subscription_id
    LEFT JOIN busy b ON b.subscription_id = d.subscription_id
    WHERE d.next_retry_at <= $2::timestamptz
      AND d.state IN ('queued', 'failed', 'delivering')
      AND s.status IN ('active', 'pending_verification')
), due AS (
    SELECT d.id
    FROM deliveries d
    JOIN ranked r ON r.id = d.id
    -- The due conditions again, on d itself: a row another instance
    -- claimed and committed while this one waited is rechecked against
    -- its new version (its lease) and skipped, never claimed twice.
    WHERE r.rn + r.busy <= $3::bigint
      AND d.next_retry_at <= $2::timestamptz
      AND d.state IN ('queued', 'failed', 'delivering')
    ORDER BY r.next_retry_at
    LIMIT $4
    FOR UPDATE OF d SKIP LOCKED
)
UPDATE deliveries d
SET state = 'delivering', next_retry_at = $1::timestamptz
FROM due, subscriptions s
WHERE d.id = due.id AND s.id = d.subscription_id
RETURNING d.id, d.subscription_id, d.change_id, d.attempts, d.created_at,
          s.callback_url, s.datasets, s.status
`

type ClaimDeliveriesParams struct {
	LeaseUntil         time.Time
	Now                time.Time
	MaxPerSubscription int64
	MaxRows            int32
}

type ClaimDeliveriesRow struct {
	ID             string
	SubscriptionID string
	ChangeID       *int64
	Attempts       int32
	CreatedAt      time.Time
	CallbackUrl    string
	Datasets       []string
	Status         string
}

// The due deliveries of receiving subscriptions, oldest due first, each
// locked against every other instance (SKIP LOCKED) and leased: the row
// is delivering until lease_until, and a lease that runs out (a process
// killed mid-attempt) makes it due again, so nothing is lost. A
// subscription gets at most max_per_subscription rows in flight, those
// already delivering under a live lease included, so one slow
// subscriber never takes every slot (D7).
func (q *Queries) ClaimDeliveries(ctx context.Context, arg ClaimDeliveriesParams) ([]ClaimDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, claimDeliveries,
		arg.LeaseUntil,
		arg.Now,
		arg.MaxPerSubscription,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimDeliveriesRow
	for rows.Next() {
		var i ClaimDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.SubscriptionID,
			&i.ChangeID,
			&i.Attempts,
			&i.CreatedAt,
			&i.CallbackUrl,
			&i.Datasets,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const finishDelivered = `-- name: FinishDelivered :one
UPDATE deliveries SET
    state = 'delivered',
    attempts = attempts + 1,
    first_attempt_at = COALESCE(first_attempt_at, $1::timestamptz),
    last_attempt_at = $1::timestamptz,
    delivered_at = $1::timestamptz,
    last_status_code = $2,
    last_error = NULL,
    next_retry_at = NULL
WHERE id = $3
RETURNING attempts
`

type FinishDeliveredParams struct {
	At         time.Time
	StatusCode *int32
	ID         string
}

func (q *Queries) FinishDelivered(ctx context.Context, arg FinishDeliveredParams) (int32, error) {
	row := q.db.QueryRow(ctx, finishDelivered, arg.At, arg.StatusCode, arg.ID)
	var attempts int32
	err := row.Scan(&attempts)
	return attempts, err
}

const finishFailed = `-- name: FinishFailed :one
UPDATE deliveries d SET
    state = CASE WHEN $1::boolean
                   OR (SELECT s.status FROM subscriptions s WHERE s.id = d.subscription_id) = 'deleted'
                 THEN 'expired' ELSE 'failed' END,
    attempts = d.attempts + 1,
    first_attempt_at = COALESCE(d.first_attempt_at, $2::timestamptz),
    last_attempt_at = $2::timestamptz,
    last_status_code = $3::integer,
    last_error = $4::text,
    next_retry_at = CASE WHEN $1::boolean THEN NULL ELSE $5::timestamptz END
WHERE d.id = $6
RETURNING d.attempts, d.state
`

type FinishFailedParams struct {
	Expire      bool
	At          time.Time
	StatusCode  *int32
	Error       string
	NextRetryAt *time.Time
	ID          string
}

type FinishFailedRow struct {
	Attempts int32
	State    string
}

// A failed attempt: failed and due again at next_retry_at, or expired
// (the window has passed, or the subscription was deleted meanwhile).
func (q *Queries) FinishFailed(ctx context.Context, arg FinishFailedParams) (FinishFailedRow, error) {
	row := q.db.QueryRow(ctx, finishFailed,
		arg.Expire,
		arg.At,
		arg.StatusCode,
		arg.Error,
		arg.NextRetryAt,
		arg.ID,
	)
	var i FinishFailedRow
	err := row.Scan(&i.Attempts, &i.State)
	return i, err
}

const getChangesByID = `-- name: GetChangesByID :many
SELECT id, dataset, version, feature_ids, removed_ids, reason, at,
       (bbox IS NOT NULL)::boolean AS has_bbox,
       COALESCE(ST_XMin(bbox), 0)::float8 AS min_lon, COALESCE(ST_YMin(bbox), 0)::float8 AS min_lat,
       COALESCE(ST_XMax(bbox), 0)::float8 AS max_lon, COALESCE(ST_YMax(bbox), 0)::float8 AS max_lat
FROM changes
WHERE id = ANY($1::bigint[])
`

type GetChangesByIDRow struct {
	ID         int64
	Dataset    string
	Version    int64
	FeatureIds []string
	RemovedIds []string
	Reason     string
	At         time.Time
	HasBbox    bool
	MinLon     float64
	MinLat     float64
	MaxLon     float64
	MaxLat     float64
}

func (q *Queries) GetChangesByID(ctx context.Context, ids []int64) ([]GetChangesByIDRow, error) {
	rows, err := q.db.Query(ctx, getChangesByID, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChangesByIDRow
	for rows.Next() {
		var i GetChangesByIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Dataset,
			&i.Version,
			&i.FeatureIds,
			&i.RemovedIds,
			&i.Reason,
			&i.At,
			&i.HasBbox,
			&i.MinLon,
			&i.MinLat,
			&i.MaxLon,
			&i.MaxLat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWatermark = `-- name: GetWatermark :one
SELECT watermark FROM deliver_state WHERE name = $1
`

func (q *Queries) GetWatermark(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRow(ctx, getWatermark, name)
	var watermark int64
	err := row.Scan(&watermark)
	return watermark, err
}

const insertChangeDelivery = `-- name: InsertChangeDelivery :execrows
INSERT INTO deliveries (id, subscription_id, change_id, state, next_retry_at, created_at)
VALUES ($1, $2, $3::bigint, 'queued', $4::timestamptz, $4::timestamptz)
ON CONFLICT (subscription_id, change_id) DO NOTHING
`

type InsertChangeDeliveryParams struct {
	ID             string
	SubscriptionID string
	ChangeID       int64
	Now            time.Time
}

// One delivery of a change to a subscription, due now. Redelivery of the
// change (JetStream, the scan, a second instance) inserts nothing (B-05).
func (q *Queries) InsertChangeDelivery(ctx context.Context, arg InsertChangeDeliveryParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertChangeDelivery,
		arg.ID,
		arg.SubscriptionID,
		arg.ChangeID,
		arg.Now,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listChangesForScan = `-- name: ListChangesForScan :many
SELECT id, dataset, version, feature_ids, removed_ids, reason, at,
       (bbox IS NOT NULL)::boolean AS has_bbox,
       COALESCE(ST_XMin(bbox), 0)::float8 AS min_lon, COALESCE(ST_YMin(bbox), 0)::float8 AS min_lat,
       COALESCE(ST_XMax(bbox), 0)::float8 AS max_lon, COALESCE(ST_YMax(bbox), 0)::float8 AS max_lat
FROM changes
WHERE id > $1 AND at < $2
ORDER BY id
LIMIT $3
`

type ListChangesForScanParams struct {
	SinceID int64
	Before  time.Time
	MaxRows int32
}

type ListChangesForScanRow struct {
	ID         int64
	Dataset    string
	Version    int64
	FeatureIds []string
	RemovedIds []string
	Reason     string
	At         time.Time
	HasBbox    bool
	MinLon     float64
	MinLat     float64
	MaxLon     float64
	MaxLat     float64
}

// The changes after the watermark committed before a cut-off (the bus
// has had its chance at the newer ones), in cursor order.
func (q *Queries) ListChangesForScan(ctx context.Context, arg ListChangesForScanParams) ([]ListChangesForScanRow, error) {
	rows, err := q.db.Query(ctx, listChangesForScan, arg.SinceID, arg.Before, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChangesForScanRow
	for rows.Next() {
		var i ListChangesForScanRow
		if err := rows.Scan(
			&i.ID,
			&i.Dataset,
			&i.Version,
			&i.FeatureIds,
			&i.RemovedIds,
			&i.Reason,
			&i.At,
			&i.HasBbox,
			&i.MinLon,
			&i.MinLat,
			&i.MaxLon,
			&i.MaxLat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDatasetVersions = `-- name: ListDatasetVersions :many
SELECT name, current_version FROM datasets
`

type ListDatasetVersionsRow struct {
	Name           string
	CurrentVersion int64
}

func (q *Queries) ListDatasetVersions(ctx context.Context) ([]ListDatasetVersionsRow, error) {
	rows, err := q.db.Query(ctx, listDatasetVersions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDatasetVersionsRow
	for rows.Next() {
		var i ListDatasetVersionsRow
		if err := rows.Scan(&i.Name, &i.CurrentVersion); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReceivingSubscriptions = `-- name: ListReceivingSubscriptions :many

SELECT id, client_id, callback_url, datasets, status, created_at,
       (bbox IS NOT NULL)::boolean AS has_bbox,
       COALESCE(ST_XMin(bbox), 0)::float8 AS min_lon, COALESCE(ST_YMin(bbox), 0)::float8 AS min_lat,
       COALESCE(ST_XMax(bbox), 0)::float8 AS max_lon, COALESCE(ST_YMax(bbox), 0)::float8 AS max_lat
FROM subscriptions
WHERE status IN ('active', 'pending_verification')
ORDER BY id
`

type ListReceivingSubscriptionsRow struct {
	ID          string
	ClientID    string
	CallbackUrl string
	Datasets    []string
	Status      string
	CreatedAt   time.Time
	HasBbox     bool
	MinLon      float64
	MinLat      float64
	MaxLon      float64
	MaxLat      float64
}

// WP-6: deliver's queries (docs/PLAN.md sections 6.5 and D6, D7). deliver
// connects as cisp_deliver: SELECT on datasets and changes, SELECT and
// UPDATE on subscriptions, SELECT, INSERT and UPDATE on deliveries and
// deliver_state (the grants of migrations 0002, 0004 and 0009).
// Every subscription that is sent notifications: active and pending.
func (q *Queries) ListReceivingSubscriptions(ctx context.Context) ([]ListReceivingSubscriptionsRow, error) {
	rows, err := q.db.Query(ctx, listReceivingSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReceivingSubscriptionsRow
	for rows.Next() {
		var i ListReceivingSubscriptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.CallbackUrl,
			&i.Datasets,
			&i.Status,
			&i.CreatedAt,
			&i.HasBbox,
			&i.MinLon,
			&i.MinLat,
			&i.MaxLon,
			&i.MaxLat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queueStats = `-- name: QueueStats :one
SELECT
    count(*) FILTER (WHERE d.state IN ('queued', 'failed'))::bigint AS queued,
    count(*) FILTER (WHERE d.state IN ('queued', 'failed') AND d.next_retry_at <= $1::timestamptz)::bigint AS due,
    count(*) FILTER (WHERE d.state = 'delivering')::bigint AS delivering,
    COALESCE(EXTRACT(EPOCH FROM ($1::timestamptz - min(d.next_retry_at) FILTER (
        WHERE d.state IN ('queued', 'failed') AND d.next_retry_at <= $1::timestamptz))), 0)::float8 AS oldest_due_age_s,
    (SELECT count(*) FROM subscriptions WHERE status = 'suspended')::bigint AS suspended
FROM deliveries d
JOIN subscriptions s ON s.id = d.subscription_id
WHERE d.state IN ('queued', 'failed', 'delivering') AND s.status IN ('active', 'pending_verification')
`

type QueueStatsRow struct {
	Queued        int64
	Due           int64
	Delivering    int64
	OldestDueAgeS float64
	Suspended     int64
}

// What the status line prints: deliveries waiting (queued or failed) and
// in flight for receiving subscriptions, those due now, the oldest due
// time's age in seconds (0 when none is due), and the suspended
// subscriptions.
func (q *Queries) QueueStats(ctx context.Context, now time.Time) (QueueStatsRow, error) {
	row := q.db.QueryRow(ctx, queueStats, now)
	var i QueueStatsRow
	err := row.Scan(
		&i.Queued,
		&i.Due,
		&i.Delivering,
		&i.OldestDueAgeS,
		&i.Suspended,
	)
	return i, err
}

const subscriptionFailed = `-- name: SubscriptionFailed :one
UPDATE subscriptions SET
    consecutive_failures = consecutive_failures + 1,
    failing_since = COALESCE(failing_since, $1::timestamptz)
WHERE id = $2
RETURNING status, consecutive_failures, failing_since
`

type SubscriptionFailedParams struct {
	At time.Time
	ID string
}

type SubscriptionFailedRow struct {
	Status              string
	ConsecutiveFailures int32
	FailingSince        *time.Time
}

func (q *Queries) SubscriptionFailed(ctx context.Context, arg SubscriptionFailedParams) (SubscriptionFailedRow, error) {
	row := q.db.QueryRow(ctx, subscriptionFailed, arg.At, arg.ID)
	var i SubscriptionFailedRow
	err := row.Scan(&i.Status, &i.ConsecutiveFailures, &i.FailingSince)
	return i, err
}

const subscriptionSucceeded = `-- name: SubscriptionSucceeded :one
UPDATE subscriptions SET
    last_success_at = $1::timestamptz,
    consecutive_failures = 0,
    failing_since = NULL,
    verified_at = CASE WHEN status = 'pending_verification' THEN $1::timestamptz ELSE verified_at END,
    status = CASE WHEN status = 'pending_verification' THEN 'active' ELSE status END
WHERE id = $2
RETURNING status, COALESCE(verified_at = $1::timestamptz, false)::boolean AS verified_now
`

type SubscriptionSucceededParams struct {
	At time.Time
	ID string
}

type SubscriptionSucceededRow struct {
	Status      string
	VerifiedNow bool
}

// A 2xx: the failure run ends, and a pending subscription is verified.
func (q *Queries) SubscriptionSucceeded(ctx context.Context, arg SubscriptionSucceededParams) (SubscriptionSucceededRow, error) {
	row := q.db.QueryRow(ctx, subscriptionSucceeded, arg.At, arg.ID)
	var i SubscriptionSucceededRow
	err := row.Scan(&i.Status, &i.VerifiedNow)
	return i, err
}

const suspendSubscription = `-- name: SuspendSubscription :execrows
UPDATE subscriptions SET status = 'suspended', suspended_reason = $1
WHERE id = $2 AND status = 'active'
`

type SuspendSubscriptionParams struct {
	Reason *string
	ID     string
}

func (q *Queries) SuspendSubscription(ctx context.Context, arg SuspendSubscriptionParams) (int64, error) {
	result, err := q.db.Exec(ctx, suspendSubscription, arg.Reason, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
