// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package relational

import (
	"context"
	"time"
)

const insertEvent = `-- name: InsertEvent :one
INSERT INTO events (ts, actor_type, actor_id, event_type, entity_type, entity_id, payload, prev_hash, hash)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id
`

type InsertEventParams struct {
	Ts         time.Time
	ActorType  string
	ActorID    string
	EventType  string
	EntityType string
	EntityID   string
	Payload    []byte
	PrevHash   []byte
	Hash       []byte
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertEvent,
		arg.Ts,
		arg.ActorType,
		arg.ActorID,
		arg.EventType,
		arg.EntityType,
		arg.EntityID,
		arg.Payload,
		arg.PrevHash,
		arg.Hash,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const lastEventHash = `-- name: LastEventHash :one
SELECT hash FROM events ORDER BY id DESC LIMIT 1
`

func (q *Queries) LastEventHash(ctx context.Context) ([]byte, error) {
	row := q.db.QueryRow(ctx, lastEventHash)
	var hash []byte
	err := row.Scan(&hash)
	return hash, err
}

const listEvents = `-- name: ListEvents :many
SELECT id, ts, actor_type, actor_id, event_type, entity_type, entity_id, payload, prev_hash, hash
FROM events
WHERE id > $1
ORDER BY id
LIMIT $2
`

type ListEventsParams struct {
	AfterID int64
	MaxRows int32
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEvents, arg.AfterID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.ActorType,
			&i.ActorID,
			&i.EventType,
			&i.EntityType,
			&i.EntityID,
			&i.Payload,
			&i.PrevHash,
			&i.Hash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockEventChain = `-- name: LockEventChain :exec

SELECT pg_advisory_xact_lock(hashtext('cisp.events')::bigint)
`

// WP-1: the audit log and its hash chain (06 T7).
// Serialises appends so each row's prev_hash is the previous row's hash.
func (q *Queries) LockEventChain(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockEventChain)
	return err
}
