// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: intake.sql

package relational

import (
	"context"
	"time"
)

const getPublisher = `-- name: GetPublisher :one
SELECT client_id, kind, mtls_subject, last_heartbeat_at, last_publication_at,
       stale_after_s, enabled, last_heartbeat_sent_at, active_refs
FROM publishers
WHERE client_id = $1
`

func (q *Queries) GetPublisher(ctx context.Context, clientID string) (Publisher, error) {
	row := q.db.QueryRow(ctx, getPublisher, clientID)
	var i Publisher
	err := row.Scan(
		&i.ClientID,
		&i.Kind,
		&i.MtlsSubject,
		&i.LastHeartbeatAt,
		&i.LastPublicationAt,
		&i.StaleAfterS,
		&i.Enabled,
		&i.LastHeartbeatSentAt,
		&i.ActiveRefs,
	)
	return i, err
}

const listPublicationVersions = `-- name: ListPublicationVersions :many
SELECT id, dataset, version, publisher_client_id, received_at, body_sha256,
       octet_length(body)::bigint AS bytes, content_type, signature_kid,
       feature_count, added, changed, removed, supersedes_version, warnings, reason
FROM publications
WHERE dataset = $1 AND version < $2
ORDER BY version DESC
LIMIT $3
`

type ListPublicationVersionsParams struct {
	Dataset       string
	BeforeVersion int64
	MaxRows       int32
}

type ListPublicationVersionsRow struct {
	ID                string
	Dataset           string
	Version           int64
	PublisherClientID string
	ReceivedAt        time.Time
	BodySha256        []byte
	Bytes             int64
	ContentType       string
	SignatureKid      *string
	FeatureCount      int32
	Added             int32
	Changed           int32
	Removed           int32
	SupersedesVersion *int64
	Warnings          []byte
	Reason            string
}

// The version history, newest first, below a version, with warnings and
// the body size; no bodies.
func (q *Queries) ListPublicationVersions(ctx context.Context, arg ListPublicationVersionsParams) ([]ListPublicationVersionsRow, error) {
	rows, err := q.db.Query(ctx, listPublicationVersions, arg.Dataset, arg.BeforeVersion, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublicationVersionsRow
	for rows.Next() {
		var i ListPublicationVersionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Dataset,
			&i.Version,
			&i.PublisherClientID,
			&i.ReceivedAt,
			&i.BodySha256,
			&i.Bytes,
			&i.ContentType,
			&i.SignatureKid,
			&i.FeatureCount,
			&i.Added,
			&i.Changed,
			&i.Removed,
			&i.SupersedesVersion,
			&i.Warnings,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRefusedAttempts = `-- name: ListRefusedAttempts :many
SELECT id, dataset, publisher_client_id, received_at, outcome, publication_id,
       problems, body_sha256, bytes
FROM publication_attempts
WHERE publisher_client_id = $1
  AND dataset = $2
  AND outcome = 'refused'
  AND received_at > $3
ORDER BY received_at DESC, id DESC
LIMIT $4
`

type ListRefusedAttemptsParams struct {
	PublisherClientID string
	Dataset           string
	Since             time.Time
	MaxRows           int32
}

// A publisher's refused attempts on a dataset after an instant, newest
// first.
func (q *Queries) ListRefusedAttempts(ctx context.Context, arg ListRefusedAttemptsParams) ([]PublicationAttempt, error) {
	rows, err := q.db.Query(ctx, listRefusedAttempts,
		arg.PublisherClientID,
		arg.Dataset,
		arg.Since,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PublicationAttempt
	for rows.Next() {
		var i PublicationAttempt
		if err := rows.Scan(
			&i.ID,
			&i.Dataset,
			&i.PublisherClientID,
			&i.ReceivedAt,
			&i.Outcome,
			&i.PublicationID,
			&i.Problems,
			&i.BodySha256,
			&i.Bytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reservedFeatureIDs = `-- name: ReservedFeatureIDs :many

SELECT feature_id, dataset
FROM features_current
WHERE dataset <> $1
  AND dataset IN ('zones', 'uspace_airspace', 'restrictions')
  AND feature_id = ANY($2::text[])
ORDER BY feature_id
`

type ReservedFeatureIDsParams struct {
	Dataset string
	Ids     []string
}

type ReservedFeatureIDsRow struct {
	FeatureID string
	Dataset   string
}

// WP-3: publication intake (docs/WORKPACKAGES/WP-3.md): the
// cross-dataset identifier lookup, the version history with warnings,
// the publisher's refused attempts and the publisher heartbeat.
// D8: which of ids the current version of another dataset already holds
// (zones, uspace_airspace and restrictions share one identifier space).
func (q *Queries) ReservedFeatureIDs(ctx context.Context, arg ReservedFeatureIDsParams) ([]ReservedFeatureIDsRow, error) {
	rows, err := q.db.Query(ctx, reservedFeatureIDs, arg.Dataset, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReservedFeatureIDsRow
	for rows.Next() {
		var i ReservedFeatureIDsRow
		if err := rows.Scan(&i.FeatureID, &i.Dataset); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPublisherHeartbeat = `-- name: UpsertPublisherHeartbeat :exec
INSERT INTO publishers (client_id, kind, last_heartbeat_at, last_heartbeat_sent_at, active_refs)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (client_id) DO UPDATE
SET kind                   = EXCLUDED.kind,
    last_heartbeat_at      = EXCLUDED.last_heartbeat_at,
    last_heartbeat_sent_at = EXCLUDED.last_heartbeat_sent_at,
    active_refs            = EXCLUDED.active_refs
`

type UpsertPublisherHeartbeatParams struct {
	ClientID   string
	Kind       string
	ReceivedAt *time.Time
	SentAt     *time.Time
	ActiveRefs []byte
}

func (q *Queries) UpsertPublisherHeartbeat(ctx context.Context, arg UpsertPublisherHeartbeatParams) error {
	_, err := q.db.Exec(ctx, upsertPublisherHeartbeat,
		arg.ClientID,
		arg.Kind,
		arg.ReceivedAt,
		arg.SentAt,
		arg.ActiveRefs,
	)
	return err
}
