// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package relational

import (
	"time"
)

type Account struct {
	ID            string
	Username      string
	PasswordHash  string
	Role          string
	TotpSecretEnc []byte
	MfaRequired   bool
	Status        string
	CreatedAt     time.Time
	LastLoginAt   *time.Time
	FailedLogins  int32
	LockedUntil   *time.Time
}

// The change feed and the outbox (D6): id is the cursor; written in the publication transaction. Insert-only.
type Change struct {
	ID            int64
	Dataset       string
	Version       int64
	PublicationID *string
	FeatureIds    []string
	RemovedIds    []string
	Reason        string
	At            time.Time
	Bbox          interface{}
}

type Dataset struct {
	Name           string
	Kind           string
	CurrentVersion int64
	PublisherKind  string
	UpdatedAt      time.Time
}

// deliver's reconciliation watermark (D6): changes up to it have their deliveries.
type DeliverState struct {
	Name      string
	Watermark int64
	UpdatedAt time.Time
}

type Delivery struct {
	ID             string
	SubscriptionID string
	// The changes.id delivered; null for the subscription_test ping of a new or changed callback.
	ChangeID       *int64
	State          string
	Attempts       int32
	FirstAttemptAt *time.Time
	LastAttemptAt  *time.Time
	NextRetryAt    *time.Time
	DeliveredAt    *time.Time
	LastStatusCode *int32
	LastError      *string
	CreatedAt      time.Time
}

// Append-only audit log with a per-row hash chain (06 T7); partitioned by month; insert-only for cisp_api.
type Event struct {
	ID         int64
	Ts         time.Time
	ActorType  string
	ActorID    string
	EventType  string
	EntityType string
	EntityID   string
	Payload    []byte
	PrevHash   []byte
	Hash       []byte
}

// The features of every version, with op against the previous one; removed rows carry the last feature. Insert-only.
type Feature struct {
	PublicationID string
	FeatureID     string
	// The feature as published (canonical compact JSON); the only geometry ever served.
	Feature       []byte
	FeatureSha256 []byte
	// DRAWING AND PREFILTER SHAPE ONLY (LESSONS Z-11): a polygon as published; a circle as ST_Buffer of its centre and radius on geography; a GeometryCollection as the union of its parts. Never served as the zone and never judged against.
	Geom           interface{}
	Centroid       interface{}
	LowerM         *float64
	LowerRef       *string
	UpperM         *float64
	UpperRef       *string
	ApplicableFrom *time.Time
	ApplicableTo   *time.Time
	HasEvents      bool
	HasLayers      bool
	Op             string
}

// The materialised current version of each dataset; replaced inside the publication transaction.
type FeaturesCurrent struct {
	Dataset       string
	FeatureID     string
	Version       int64
	Feature       []byte
	FeatureSha256 []byte
	// DRAWING AND PREFILTER SHAPE ONLY (LESSONS Z-11): a circle is its centre and radius; this buffer exists for bbox prefilters and drawing and is never served as the zone.
	Geom           interface{}
	Centroid       interface{}
	LowerM         *float64
	LowerRef       *string
	UpperM         *float64
	UpperRef       *string
	ApplicableFrom *time.Time
	ApplicableTo   *time.Time
	HasEvents      bool
	HasLayers      bool
}

// The last run of each leader-elected api job (restriction_expiry), shared by the replicas.
type JobRun struct {
	Name         string
	LastRunAt    time.Time
	LastInstance string
	LastCount    int32
}

// Every accepted version with the verbatim body and the publisher signature; insert-only, kept for ever (06 T7, 05 section 4).
type Publication struct {
	ID                 string
	Dataset            string
	Version            int64
	PublisherClientID  string
	ReceivedAt         time.Time
	Body               []byte
	BodySha256         []byte
	ContentType        string
	PublisherSignature *string
	SignatureKid       *string
	FeatureCount       int32
	Added              int32
	Changed            int32
	Removed            int32
	SupersedesVersion  *int64
	Warnings           []byte
	Reason             string
}

// Every publication attempt with its outcome and problems (Annex III A(5)); insert-only.
type PublicationAttempt struct {
	ID                string
	Dataset           string
	PublisherClientID string
	ReceivedAt        time.Time
	Outcome           string
	PublicationID     *string
	Problems          []byte
	BodySha256        []byte
	Bytes             int64
}

type Publisher struct {
	ClientID            string
	Kind                string
	MtlsSubject         *string
	LastHeartbeatAt     *time.Time
	LastPublicationAt   *time.Time
	StaleAfterS         int32
	Enabled             bool
	LastHeartbeatSentAt *time.Time
	ActiveRefs          []byte
}

type Restriction struct {
	ID                    string
	AnspRef               string
	AnspVersion           int32
	UspaceAirspaceID      string
	FeatureID             string
	State                 string
	StartsAt              time.Time
	EndsAt                time.Time
	EndedBy               *string
	CreatedAt             time.Time
	UpdatedAt             time.Time
	LastPublisherClientID string
	SourceStaleSince      *time.Time
	LastBodySha256        []byte
}

// Every lifecycle event of every restriction with its version's publication; insert-only.
type RestrictionEvent struct {
	RestrictionID string
	At            time.Time
	Op            string
	AnspVersion   int32
	PublicationID *string
	Actor         string
}

type Session struct {
	Jti       string
	AccountID string
	IssuedAt  time.Time
	ExpiresAt time.Time
	RevokedAt *time.Time
}

// The unfiltered GET /v1/{dataset} body of each version, gzip, with the CISP compact detached JWS over the uncompressed body.
type Snapshot struct {
	Dataset       string
	Version       int64
	Etag          string
	BodyGz        []byte
	CispSignature string
	BuiltAt       time.Time
}

type Subscription struct {
	ID                  string
	ClientID            string
	CallbackUrl         string
	Datasets            []string
	Bbox                interface{}
	Status              string
	CreatedAt           time.Time
	VerifiedAt          *time.Time
	SuspendedReason     *string
	ConsecutiveFailures int32
	LastSuccessAt       *time.Time
	FailingSince        *time.Time
}
