// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: publications.sql

package relational

import (
	"context"
	"time"
)

const currentFeatureHashes = `-- name: CurrentFeatureHashes :many
SELECT feature_id, feature_sha256
FROM features_current
WHERE dataset = $1
ORDER BY feature_id
`

type CurrentFeatureHashesRow struct {
	FeatureID     string
	FeatureSha256 []byte
}

func (q *Queries) CurrentFeatureHashes(ctx context.Context, dataset string) ([]CurrentFeatureHashesRow, error) {
	rows, err := q.db.Query(ctx, currentFeatureHashes, dataset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CurrentFeatureHashesRow
	for rows.Next() {
		var i CurrentFeatureHashesRow
		if err := rows.Scan(&i.FeatureID, &i.FeatureSha256); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const currentFeaturesByID = `-- name: CurrentFeaturesByID :many
SELECT feature_id, feature
FROM features_current
WHERE dataset = $1 AND feature_id = ANY($2::text[])
ORDER BY feature_id
`

type CurrentFeaturesByIDParams struct {
	Dataset string
	Ids     []string
}

type CurrentFeaturesByIDRow struct {
	FeatureID string
	Feature   []byte
}

func (q *Queries) CurrentFeaturesByID(ctx context.Context, arg CurrentFeaturesByIDParams) ([]CurrentFeaturesByIDRow, error) {
	rows, err := q.db.Query(ctx, currentFeaturesByID, arg.Dataset, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CurrentFeaturesByIDRow
	for rows.Next() {
		var i CurrentFeaturesByIDRow
		if err := rows.Scan(&i.FeatureID, &i.Feature); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteCurrentFeatures = `-- name: DeleteCurrentFeatures :execrows
DELETE FROM features_current WHERE dataset = $1
`

func (q *Queries) DeleteCurrentFeatures(ctx context.Context, dataset string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCurrentFeatures, dataset)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSnapshot = `-- name: DeleteSnapshot :execrows
DELETE FROM snapshots WHERE dataset = $1 AND version = $2
`

type DeleteSnapshotParams struct {
	Dataset string
	Version int64
}

func (q *Queries) DeleteSnapshot(ctx context.Context, arg DeleteSnapshotParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSnapshot, arg.Dataset, arg.Version)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDataset = `-- name: GetDataset :one
SELECT name, kind, current_version, publisher_kind, updated_at
FROM datasets
WHERE name = $1
`

func (q *Queries) GetDataset(ctx context.Context, name string) (Dataset, error) {
	row := q.db.QueryRow(ctx, getDataset, name)
	var i Dataset
	err := row.Scan(
		&i.Name,
		&i.Kind,
		&i.CurrentVersion,
		&i.PublisherKind,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublication = `-- name: GetPublication :one
SELECT id, dataset, version, publisher_client_id, received_at, body, body_sha256,
       content_type, publisher_signature, signature_kid, feature_count, added,
       changed, removed, supersedes_version, warnings, reason
FROM publications
WHERE dataset = $1 AND version = $2
`

type GetPublicationParams struct {
	Dataset string
	Version int64
}

func (q *Queries) GetPublication(ctx context.Context, arg GetPublicationParams) (Publication, error) {
	row := q.db.QueryRow(ctx, getPublication, arg.Dataset, arg.Version)
	var i Publication
	err := row.Scan(
		&i.ID,
		&i.Dataset,
		&i.Version,
		&i.PublisherClientID,
		&i.ReceivedAt,
		&i.Body,
		&i.BodySha256,
		&i.ContentType,
		&i.PublisherSignature,
		&i.SignatureKid,
		&i.FeatureCount,
		&i.Added,
		&i.Changed,
		&i.Removed,
		&i.SupersedesVersion,
		&i.Warnings,
		&i.Reason,
	)
	return i, err
}

const getSnapshot = `-- name: GetSnapshot :one
SELECT dataset, version, etag, body_gz, cisp_signature, built_at
FROM snapshots
WHERE dataset = $1 AND version = $2
`

type GetSnapshotParams struct {
	Dataset string
	Version int64
}

func (q *Queries) GetSnapshot(ctx context.Context, arg GetSnapshotParams) (Snapshot, error) {
	row := q.db.QueryRow(ctx, getSnapshot, arg.Dataset, arg.Version)
	var i Snapshot
	err := row.Scan(
		&i.Dataset,
		&i.Version,
		&i.Etag,
		&i.BodyGz,
		&i.CispSignature,
		&i.BuiltAt,
	)
	return i, err
}

const insertChange = `-- name: InsertChange :one
INSERT INTO changes (dataset, version, publication_id, feature_ids, removed_ids, reason, at, bbox)
VALUES (
    $1, $2, $3, $4::text[],
    $5::text[], $6, $7,
    CASE WHEN $8::boolean
         THEN ST_MakeEnvelope($9::float8, $10::float8,
                              $11::float8, $12::float8, 4326)
    END
)
RETURNING id
`

type InsertChangeParams struct {
	Dataset       string
	Version       int64
	PublicationID *string
	FeatureIds    []string
	RemovedIds    []string
	Reason        string
	At            time.Time
	HasBbox       bool
	MinLon        float64
	MinLat        float64
	MaxLon        float64
	MaxLat        float64
}

func (q *Queries) InsertChange(ctx context.Context, arg InsertChangeParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertChange,
		arg.Dataset,
		arg.Version,
		arg.PublicationID,
		arg.FeatureIds,
		arg.RemovedIds,
		arg.Reason,
		arg.At,
		arg.HasBbox,
		arg.MinLon,
		arg.MinLat,
		arg.MaxLon,
		arg.MaxLat,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertCurrentFromPublication = `-- name: InsertCurrentFromPublication :execrows
INSERT INTO features_current (
    dataset, feature_id, version, feature, feature_sha256, geom, centroid,
    lower_m, lower_ref, upper_m, upper_ref, applicable_from, applicable_to,
    has_events, has_layers
)
SELECT $1, feature_id, $2, feature, feature_sha256, geom, centroid,
       lower_m, lower_ref, upper_m, upper_ref, applicable_from, applicable_to,
       has_events, has_layers
FROM features
WHERE publication_id = $3 AND op <> 'removed'
`

type InsertCurrentFromPublicationParams struct {
	Dataset       string
	Version       int64
	PublicationID string
}

func (q *Queries) InsertCurrentFromPublication(ctx context.Context, arg InsertCurrentFromPublicationParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertCurrentFromPublication, arg.Dataset, arg.Version, arg.PublicationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertPublication = `-- name: InsertPublication :exec
INSERT INTO publications (
    id, dataset, version, publisher_client_id, received_at, body, body_sha256,
    content_type, publisher_signature, signature_kid, feature_count, added,
    changed, removed, supersedes_version, warnings, reason
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17
)
`

type InsertPublicationParams struct {
	ID                 string
	Dataset            string
	Version            int64
	PublisherClientID  string
	ReceivedAt         time.Time
	Body               []byte
	BodySha256         []byte
	ContentType        string
	PublisherSignature *string
	SignatureKid       *string
	FeatureCount       int32
	Added              int32
	Changed            int32
	Removed            int32
	SupersedesVersion  *int64
	Warnings           []byte
	Reason             string
}

func (q *Queries) InsertPublication(ctx context.Context, arg InsertPublicationParams) error {
	_, err := q.db.Exec(ctx, insertPublication,
		arg.ID,
		arg.Dataset,
		arg.Version,
		arg.PublisherClientID,
		arg.ReceivedAt,
		arg.Body,
		arg.BodySha256,
		arg.ContentType,
		arg.PublisherSignature,
		arg.SignatureKid,
		arg.FeatureCount,
		arg.Added,
		arg.Changed,
		arg.Removed,
		arg.SupersedesVersion,
		arg.Warnings,
		arg.Reason,
	)
	return err
}

const insertPublicationAttempt = `-- name: InsertPublicationAttempt :exec
INSERT INTO publication_attempts (
    id, dataset, publisher_client_id, received_at, outcome, publication_id,
    problems, body_sha256, bytes
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertPublicationAttemptParams struct {
	ID                string
	Dataset           string
	PublisherClientID string
	ReceivedAt        time.Time
	Outcome           string
	PublicationID     *string
	Problems          []byte
	BodySha256        []byte
	Bytes             int64
}

func (q *Queries) InsertPublicationAttempt(ctx context.Context, arg InsertPublicationAttemptParams) error {
	_, err := q.db.Exec(ctx, insertPublicationAttempt,
		arg.ID,
		arg.Dataset,
		arg.PublisherClientID,
		arg.ReceivedAt,
		arg.Outcome,
		arg.PublicationID,
		arg.Problems,
		arg.BodySha256,
		arg.Bytes,
	)
	return err
}

const insertRemovedFeatures = `-- name: InsertRemovedFeatures :execrows
INSERT INTO features (
    publication_id, feature_id, feature, feature_sha256, geom, centroid,
    lower_m, lower_ref, upper_m, upper_ref, applicable_from, applicable_to,
    has_events, has_layers, op
)
SELECT $1, feature_id, feature, feature_sha256, geom, centroid,
       lower_m, lower_ref, upper_m, upper_ref, applicable_from, applicable_to,
       has_events, has_layers, 'removed'
FROM features_current
WHERE dataset = $2 AND feature_id = ANY($3::text[])
`

type InsertRemovedFeaturesParams struct {
	PublicationID string
	Dataset       string
	Ids           []string
}

// A removed feature keeps its last published form in the new version,
// for the delta.
func (q *Queries) InsertRemovedFeatures(ctx context.Context, arg InsertRemovedFeaturesParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertRemovedFeatures, arg.PublicationID, arg.Dataset, arg.Ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertSnapshot = `-- name: InsertSnapshot :exec
INSERT INTO snapshots (dataset, version, etag, body_gz, cisp_signature, built_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertSnapshotParams struct {
	Dataset       string
	Version       int64
	Etag          string
	BodyGz        []byte
	CispSignature string
	BuiltAt       time.Time
}

func (q *Queries) InsertSnapshot(ctx context.Context, arg InsertSnapshotParams) error {
	_, err := q.db.Exec(ctx, insertSnapshot,
		arg.Dataset,
		arg.Version,
		arg.Etag,
		arg.BodyGz,
		arg.CispSignature,
		arg.BuiltAt,
	)
	return err
}

const listChanges = `-- name: ListChanges :many
SELECT id, dataset, version, publication_id, feature_ids, removed_ids, reason, at,
       (bbox IS NOT NULL)::boolean AS has_bbox,
       COALESCE(ST_XMin(bbox), 0)::float8 AS min_lon, COALESCE(ST_YMin(bbox), 0)::float8 AS min_lat,
       COALESCE(ST_XMax(bbox), 0)::float8 AS max_lon, COALESCE(ST_YMax(bbox), 0)::float8 AS max_lat
FROM changes
WHERE id > $1 AND ($2::text IS NULL OR dataset = $2)
ORDER BY id
LIMIT $3
`

type ListChangesParams struct {
	SinceID int64
	Dataset *string
	MaxRows int32
}

type ListChangesRow struct {
	ID            int64
	Dataset       string
	Version       int64
	PublicationID *string
	FeatureIds    []string
	RemovedIds    []string
	Reason        string
	At            time.Time
	HasBbox       bool
	MinLon        float64
	MinLat        float64
	MaxLon        float64
	MaxLat        float64
}

// The change feed after a cursor, optionally for one dataset.
func (q *Queries) ListChanges(ctx context.Context, arg ListChangesParams) ([]ListChangesRow, error) {
	rows, err := q.db.Query(ctx, listChanges, arg.SinceID, arg.Dataset, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChangesRow
	for rows.Next() {
		var i ListChangesRow
		if err := rows.Scan(
			&i.ID,
			&i.Dataset,
			&i.Version,
			&i.PublicationID,
			&i.FeatureIds,
			&i.RemovedIds,
			&i.Reason,
			&i.At,
			&i.HasBbox,
			&i.MinLon,
			&i.MinLat,
			&i.MaxLon,
			&i.MaxLat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrentFeatures = `-- name: ListCurrentFeatures :many
SELECT feature_id, version, feature, feature_sha256,
       ST_Y(centroid)::float8 AS centroid_lat, ST_X(centroid)::float8 AS centroid_lon,
       lower_m, lower_ref, upper_m, upper_ref, applicable_from, applicable_to,
       has_events, has_layers
FROM features_current
WHERE dataset = $1
ORDER BY feature_id
`

type ListCurrentFeaturesRow struct {
	FeatureID      string
	Version        int64
	Feature        []byte
	FeatureSha256  []byte
	CentroidLat    float64
	CentroidLon    float64
	LowerM         *float64
	LowerRef       *string
	UpperM         *float64
	UpperRef       *string
	ApplicableFrom *time.Time
	ApplicableTo   *time.Time
	HasEvents      bool
	HasLayers      bool
}

func (q *Queries) ListCurrentFeatures(ctx context.Context, dataset string) ([]ListCurrentFeaturesRow, error) {
	rows, err := q.db.Query(ctx, listCurrentFeatures, dataset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCurrentFeaturesRow
	for rows.Next() {
		var i ListCurrentFeaturesRow
		if err := rows.Scan(
			&i.FeatureID,
			&i.Version,
			&i.Feature,
			&i.FeatureSha256,
			&i.CentroidLat,
			&i.CentroidLon,
			&i.LowerM,
			&i.LowerRef,
			&i.UpperM,
			&i.UpperRef,
			&i.ApplicableFrom,
			&i.ApplicableTo,
			&i.HasEvents,
			&i.HasLayers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDatasets = `-- name: ListDatasets :many
SELECT name, kind, current_version, publisher_kind, updated_at
FROM datasets
ORDER BY name
`

func (q *Queries) ListDatasets(ctx context.Context) ([]Dataset, error) {
	rows, err := q.db.Query(ctx, listDatasets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Dataset
	for rows.Next() {
		var i Dataset
		if err := rows.Scan(
			&i.Name,
			&i.Kind,
			&i.CurrentVersion,
			&i.PublisherKind,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicationAttempts = `-- name: ListPublicationAttempts :many
SELECT id, dataset, publisher_client_id, received_at, outcome, publication_id,
       problems, body_sha256, bytes
FROM publication_attempts
WHERE publisher_client_id = $1 AND dataset = $2
ORDER BY received_at DESC
LIMIT $3
`

type ListPublicationAttemptsParams struct {
	PublisherClientID string
	Dataset           string
	MaxRows           int32
}

func (q *Queries) ListPublicationAttempts(ctx context.Context, arg ListPublicationAttemptsParams) ([]PublicationAttempt, error) {
	rows, err := q.db.Query(ctx, listPublicationAttempts, arg.PublisherClientID, arg.Dataset, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PublicationAttempt
	for rows.Next() {
		var i PublicationAttempt
		if err := rows.Scan(
			&i.ID,
			&i.Dataset,
			&i.PublisherClientID,
			&i.ReceivedAt,
			&i.Outcome,
			&i.PublicationID,
			&i.Problems,
			&i.BodySha256,
			&i.Bytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicationFeatures = `-- name: ListPublicationFeatures :many
SELECT feature_id, feature, feature_sha256, op
FROM features
WHERE publication_id = $1
ORDER BY feature_id
`

type ListPublicationFeaturesRow struct {
	FeatureID     string
	Feature       []byte
	FeatureSha256 []byte
	Op            string
}

func (q *Queries) ListPublicationFeatures(ctx context.Context, publicationID string) ([]ListPublicationFeaturesRow, error) {
	rows, err := q.db.Query(ctx, listPublicationFeatures, publicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublicationFeaturesRow
	for rows.Next() {
		var i ListPublicationFeaturesRow
		if err := rows.Scan(
			&i.FeatureID,
			&i.Feature,
			&i.FeatureSha256,
			&i.Op,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublications = `-- name: ListPublications :many
SELECT id, dataset, version, publisher_client_id, received_at, body_sha256,
       content_type, signature_kid, feature_count, added, changed, removed,
       supersedes_version, reason
FROM publications
WHERE dataset = $1 AND version < $2
ORDER BY version DESC
LIMIT $3
`

type ListPublicationsParams struct {
	Dataset       string
	BeforeVersion int64
	MaxRows       int32
}

type ListPublicationsRow struct {
	ID                string
	Dataset           string
	Version           int64
	PublisherClientID string
	ReceivedAt        time.Time
	BodySha256        []byte
	ContentType       string
	SignatureKid      *string
	FeatureCount      int32
	Added             int32
	Changed           int32
	Removed           int32
	SupersedesVersion *int64
	Reason            string
}

// The version history without bodies, newest first, below a version.
func (q *Queries) ListPublications(ctx context.Context, arg ListPublicationsParams) ([]ListPublicationsRow, error) {
	rows, err := q.db.Query(ctx, listPublications, arg.Dataset, arg.BeforeVersion, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublicationsRow
	for rows.Next() {
		var i ListPublicationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Dataset,
			&i.Version,
			&i.PublisherClientID,
			&i.ReceivedAt,
			&i.BodySha256,
			&i.ContentType,
			&i.SignatureKid,
			&i.FeatureCount,
			&i.Added,
			&i.Changed,
			&i.Removed,
			&i.SupersedesVersion,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDataset = `-- name: LockDataset :exec

SELECT pg_advisory_xact_lock(hashtext('cisp.publication.' || $1::text)::bigint)
`

// WP-1: datasets, publications, publication attempts, features,
// features_current, snapshots and changes. Later work packages add their
// own files beside this one and do not edit it.
// Serialises the publications of one dataset until the transaction
// ends, so its version and the change cursor stay monotonic.
func (q *Queries) LockDataset(ctx context.Context, dataset string) error {
	_, err := q.db.Exec(ctx, lockDataset, dataset)
	return err
}

const setDatasetVersion = `-- name: SetDatasetVersion :exec
UPDATE datasets
SET current_version = $1, updated_at = $2
WHERE name = $3
`

type SetDatasetVersionParams struct {
	Version   int64
	UpdatedAt time.Time
	Name      string
}

func (q *Queries) SetDatasetVersion(ctx context.Context, arg SetDatasetVersionParams) error {
	_, err := q.db.Exec(ctx, setDatasetVersion, arg.Version, arg.UpdatedAt, arg.Name)
	return err
}
