// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reads.sql

package relational

import (
	"context"
	"time"
)

const getSnapshotForRead = `-- name: GetSnapshotForRead :one

SELECT s.dataset, s.version, s.etag, s.body_gz,
       COALESCE((SELECT ss.signature FROM snapshot_signatures ss
                 WHERE ss.dataset = s.dataset AND ss.version = s.version
                   AND ss.body_gz_sha256 = sha256(s.body_gz)
                 ORDER BY ss.signed_at DESC, ss.id DESC LIMIT 1),
                s.cisp_signature)::text AS cisp_signature,
       s.built_at,
       p.received_at, p.publisher_client_id
FROM snapshots s
JOIN publications p ON p.dataset = s.dataset AND p.version = s.version
WHERE s.dataset = $1 AND s.version = $2
`

type GetSnapshotForReadParams struct {
	Dataset string
	Version int64
}

type GetSnapshotForReadRow struct {
	Dataset           string
	Version           int64
	Etag              string
	BodyGz            []byte
	CispSignature     string
	BuiltAt           time.Time
	ReceivedAt        time.Time
	PublisherClientID string
}

// WP-4: the reads (docs/WORKPACKAGES/WP-4.md): the snapshot with its
// version's time and publisher, the current features by bounding box,
// the features of a past version for since_version, and the publishers
// for GET /v1/status.
// One stored snapshot with the received_at (metadata.issued and
// Last-Modified) and the publisher of its version. cisp_signature is
// the newest re-signature of these exact bytes (cispctl resign-current,
// 0014), or the one the snapshot was built with.
func (q *Queries) GetSnapshotForRead(ctx context.Context, arg GetSnapshotForReadParams) (GetSnapshotForReadRow, error) {
	row := q.db.QueryRow(ctx, getSnapshotForRead, arg.Dataset, arg.Version)
	var i GetSnapshotForReadRow
	err := row.Scan(
		&i.Dataset,
		&i.Version,
		&i.Etag,
		&i.BodyGz,
		&i.CispSignature,
		&i.BuiltAt,
		&i.ReceivedAt,
		&i.PublisherClientID,
	)
	return i, err
}

const getVersionHead = `-- name: GetVersionHead :one
SELECT received_at, publisher_client_id
FROM publications
WHERE dataset = $1 AND version = $2
`

type GetVersionHeadParams struct {
	Dataset string
	Version int64
}

type GetVersionHeadRow struct {
	ReceivedAt        time.Time
	PublisherClientID string
}

// When a version was received and from whom; no body.
func (q *Queries) GetVersionHead(ctx context.Context, arg GetVersionHeadParams) (GetVersionHeadRow, error) {
	row := q.db.QueryRow(ctx, getVersionHead, arg.Dataset, arg.Version)
	var i GetVersionHeadRow
	err := row.Scan(&i.ReceivedAt, &i.PublisherClientID)
	return i, err
}

const listCurrentFeatureBodies = `-- name: ListCurrentFeatureBodies :many
SELECT feature_id, version, feature, feature_sha256
FROM features_current
WHERE dataset = $1
ORDER BY feature_id
`

type ListCurrentFeatureBodiesRow struct {
	FeatureID     string
	Version       int64
	Feature       []byte
	FeatureSha256 []byte
}

// Every current feature of a dataset as stored.
func (q *Queries) ListCurrentFeatureBodies(ctx context.Context, dataset string) ([]ListCurrentFeatureBodiesRow, error) {
	rows, err := q.db.Query(ctx, listCurrentFeatureBodies, dataset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCurrentFeatureBodiesRow
	for rows.Next() {
		var i ListCurrentFeatureBodiesRow
		if err := rows.Scan(
			&i.FeatureID,
			&i.Version,
			&i.Feature,
			&i.FeatureSha256,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrentFeaturesInBBox = `-- name: ListCurrentFeaturesInBBox :many
SELECT feature_id, version, feature, feature_sha256
FROM features_current
WHERE dataset = $1
  AND geom && ST_MakeEnvelope($2::float8, $3::float8,
                              $4::float8, $5::float8, 4326)
ORDER BY feature_id
`

type ListCurrentFeaturesInBBoxParams struct {
	Dataset string
	MinLon  float64
	MinLat  float64
	MaxLon  float64
	MaxLat  float64
}

type ListCurrentFeaturesInBBoxRow struct {
	FeatureID     string
	Version       int64
	Feature       []byte
	FeatureSha256 []byte
}

// The current features whose stored shape's bounding box overlaps the
// envelope: a prefilter on the GiST index, never a judgement (Z-06,
// Z-11; a circle is its stored buffer).
func (q *Queries) ListCurrentFeaturesInBBox(ctx context.Context, arg ListCurrentFeaturesInBBoxParams) ([]ListCurrentFeaturesInBBoxRow, error) {
	rows, err := q.db.Query(ctx, listCurrentFeaturesInBBox,
		arg.Dataset,
		arg.MinLon,
		arg.MinLat,
		arg.MaxLon,
		arg.MaxLat,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCurrentFeaturesInBBoxRow
	for rows.Next() {
		var i ListCurrentFeaturesInBBoxRow
		if err := rows.Scan(
			&i.FeatureID,
			&i.Version,
			&i.Feature,
			&i.FeatureSha256,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishers = `-- name: ListPublishers :many
SELECT client_id, kind, last_heartbeat_at, last_publication_at, stale_after_s, enabled
FROM publishers
ORDER BY client_id
`

type ListPublishersRow struct {
	ClientID          string
	Kind              string
	LastHeartbeatAt   *time.Time
	LastPublicationAt *time.Time
	StaleAfterS       int32
	Enabled           bool
}

func (q *Queries) ListPublishers(ctx context.Context) ([]ListPublishersRow, error) {
	rows, err := q.db.Query(ctx, listPublishers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishersRow
	for rows.Next() {
		var i ListPublishersRow
		if err := rows.Scan(
			&i.ClientID,
			&i.Kind,
			&i.LastHeartbeatAt,
			&i.LastPublicationAt,
			&i.StaleAfterS,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVersionFeatures = `-- name: ListVersionFeatures :many
SELECT f.feature_id, f.feature, f.feature_sha256
FROM features f
JOIN publications p ON p.id = f.publication_id
WHERE p.dataset = $1 AND p.version = $2 AND f.op <> 'removed'
ORDER BY f.feature_id
`

type ListVersionFeaturesParams struct {
	Dataset string
	Version int64
}

type ListVersionFeaturesRow struct {
	FeatureID     string
	Feature       []byte
	FeatureSha256 []byte
}

// Every feature a past version held (the removed rows of that version
// are what it dropped, so they are left out).
func (q *Queries) ListVersionFeatures(ctx context.Context, arg ListVersionFeaturesParams) ([]ListVersionFeaturesRow, error) {
	rows, err := q.db.Query(ctx, listVersionFeatures, arg.Dataset, arg.Version)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVersionFeaturesRow
	for rows.Next() {
		var i ListVersionFeaturesRow
		if err := rows.Scan(&i.FeatureID, &i.Feature, &i.FeatureSha256); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
