// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: restrictions.sql

package relational

import (
	"context"
	"time"
)

const countActiveRestrictions = `-- name: CountActiveRestrictions :one
SELECT count(*)::bigint FROM restrictions WHERE state = 'active'
`

func (q *Queries) CountActiveRestrictions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveRestrictions)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getJobRun = `-- name: GetJobRun :one
SELECT name, last_run_at, last_instance, last_count
FROM job_runs
WHERE name = $1
`

func (q *Queries) GetJobRun(ctx context.Context, name string) (JobRun, error) {
	row := q.db.QueryRow(ctx, getJobRun, name)
	var i JobRun
	err := row.Scan(
		&i.Name,
		&i.LastRunAt,
		&i.LastInstance,
		&i.LastCount,
	)
	return i, err
}

const getRestrictionByAnspRef = `-- name: GetRestrictionByAnspRef :one
SELECT id, ansp_ref, ansp_version, uspace_airspace_id, feature_id, state, starts_at, ends_at,
       ended_by, created_at, updated_at, last_publisher_client_id, last_body_sha256
FROM restrictions
WHERE ansp_ref = $1
`

type GetRestrictionByAnspRefRow struct {
	ID                    string
	AnspRef               string
	AnspVersion           int32
	UspaceAirspaceID      string
	FeatureID             string
	State                 string
	StartsAt              time.Time
	EndsAt                time.Time
	EndedBy               *string
	CreatedAt             time.Time
	UpdatedAt             time.Time
	LastPublisherClientID string
	LastBodySha256        []byte
}

func (q *Queries) GetRestrictionByAnspRef(ctx context.Context, anspRef string) (GetRestrictionByAnspRefRow, error) {
	row := q.db.QueryRow(ctx, getRestrictionByAnspRef, anspRef)
	var i GetRestrictionByAnspRefRow
	err := row.Scan(
		&i.ID,
		&i.AnspRef,
		&i.AnspVersion,
		&i.UspaceAirspaceID,
		&i.FeatureID,
		&i.State,
		&i.StartsAt,
		&i.EndsAt,
		&i.EndedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastPublisherClientID,
		&i.LastBodySha256,
	)
	return i, err
}

const getRestrictionByFeatureID = `-- name: GetRestrictionByFeatureID :one
SELECT id, ansp_ref, ansp_version, uspace_airspace_id, feature_id, state, starts_at, ends_at,
       ended_by, created_at, updated_at, last_publisher_client_id, last_body_sha256
FROM restrictions
WHERE feature_id = $1
`

type GetRestrictionByFeatureIDRow struct {
	ID                    string
	AnspRef               string
	AnspVersion           int32
	UspaceAirspaceID      string
	FeatureID             string
	State                 string
	StartsAt              time.Time
	EndsAt                time.Time
	EndedBy               *string
	CreatedAt             time.Time
	UpdatedAt             time.Time
	LastPublisherClientID string
	LastBodySha256        []byte
}

func (q *Queries) GetRestrictionByFeatureID(ctx context.Context, featureID string) (GetRestrictionByFeatureIDRow, error) {
	row := q.db.QueryRow(ctx, getRestrictionByFeatureID, featureID)
	var i GetRestrictionByFeatureIDRow
	err := row.Scan(
		&i.ID,
		&i.AnspRef,
		&i.AnspVersion,
		&i.UspaceAirspaceID,
		&i.FeatureID,
		&i.State,
		&i.StartsAt,
		&i.EndsAt,
		&i.EndedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastPublisherClientID,
		&i.LastBodySha256,
	)
	return i, err
}

const getRestrictionByID = `-- name: GetRestrictionByID :one

SELECT id, ansp_ref, ansp_version, uspace_airspace_id, feature_id, state, starts_at, ends_at,
       ended_by, created_at, updated_at, last_publisher_client_id, last_body_sha256
FROM restrictions
WHERE id = $1
`

type GetRestrictionByIDRow struct {
	ID                    string
	AnspRef               string
	AnspVersion           int32
	UspaceAirspaceID      string
	FeatureID             string
	State                 string
	StartsAt              time.Time
	EndsAt                time.Time
	EndedBy               *string
	CreatedAt             time.Time
	UpdatedAt             time.Time
	LastPublisherClientID string
	LastBodySha256        []byte
}

// WP-5: dynamic restrictions (docs/WORKPACKAGES/WP-5.md): the lifecycle
// heads, their events, the expiry's leader lock and last run, and the
// active references the ANSP's heartbeat is compared with.
func (q *Queries) GetRestrictionByID(ctx context.Context, id string) (GetRestrictionByIDRow, error) {
	row := q.db.QueryRow(ctx, getRestrictionByID, id)
	var i GetRestrictionByIDRow
	err := row.Scan(
		&i.ID,
		&i.AnspRef,
		&i.AnspVersion,
		&i.UspaceAirspaceID,
		&i.FeatureID,
		&i.State,
		&i.StartsAt,
		&i.EndsAt,
		&i.EndedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastPublisherClientID,
		&i.LastBodySha256,
	)
	return i, err
}

const insertRestriction = `-- name: InsertRestriction :exec
INSERT INTO restrictions (
    id, ansp_ref, ansp_version, uspace_airspace_id, feature_id, state, starts_at, ends_at,
    ended_by, created_at, updated_at, last_publisher_client_id, last_body_sha256
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
`

type InsertRestrictionParams struct {
	ID                    string
	AnspRef               string
	AnspVersion           int32
	UspaceAirspaceID      string
	FeatureID             string
	State                 string
	StartsAt              time.Time
	EndsAt                time.Time
	EndedBy               *string
	CreatedAt             time.Time
	UpdatedAt             time.Time
	LastPublisherClientID string
	LastBodySha256        []byte
}

func (q *Queries) InsertRestriction(ctx context.Context, arg InsertRestrictionParams) error {
	_, err := q.db.Exec(ctx, insertRestriction,
		arg.ID,
		arg.AnspRef,
		arg.AnspVersion,
		arg.UspaceAirspaceID,
		arg.FeatureID,
		arg.State,
		arg.StartsAt,
		arg.EndsAt,
		arg.EndedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.LastPublisherClientID,
		arg.LastBodySha256,
	)
	return err
}

const insertRestrictionEvent = `-- name: InsertRestrictionEvent :exec
INSERT INTO restriction_events (restriction_id, at, op, ansp_version, publication_id, actor)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertRestrictionEventParams struct {
	RestrictionID string
	At            time.Time
	Op            string
	AnspVersion   int32
	PublicationID *string
	Actor         string
}

func (q *Queries) InsertRestrictionEvent(ctx context.Context, arg InsertRestrictionEventParams) error {
	_, err := q.db.Exec(ctx, insertRestrictionEvent,
		arg.RestrictionID,
		arg.At,
		arg.Op,
		arg.AnspVersion,
		arg.PublicationID,
		arg.Actor,
	)
	return err
}

const listActiveRestrictionRefs = `-- name: ListActiveRestrictionRefs :many
SELECT ansp_ref
FROM restrictions
WHERE state = 'active'
ORDER BY ansp_ref
`

func (q *Queries) ListActiveRestrictionRefs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listActiveRestrictionRefs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var ansp_ref string
		if err := rows.Scan(&ansp_ref); err != nil {
			return nil, err
		}
		items = append(items, ansp_ref)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredRestrictions = `-- name: ListExpiredRestrictions :many
SELECT id
FROM restrictions
WHERE state = 'active' AND ends_at <= $1
ORDER BY ends_at, id
LIMIT $2
`

type ListExpiredRestrictionsParams struct {
	Now     time.Time
	MaxRows int32
}

// The active heads whose ends_at is not after now: the expiry's work.
func (q *Queries) ListExpiredRestrictions(ctx context.Context, arg ListExpiredRestrictionsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listExpiredRestrictions, arg.Now, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublisherRefs = `-- name: ListPublisherRefs :many
SELECT client_id, kind, last_heartbeat_at, stale_after_s, active_refs
FROM publishers
ORDER BY client_id
`

type ListPublisherRefsRow struct {
	ClientID        string
	Kind            string
	LastHeartbeatAt *time.Time
	StaleAfterS     int32
	ActiveRefs      []byte
}

// The publishers with what their last heartbeat declared.
func (q *Queries) ListPublisherRefs(ctx context.Context) ([]ListPublisherRefsRow, error) {
	rows, err := q.db.Query(ctx, listPublisherRefs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublisherRefsRow
	for rows.Next() {
		var i ListPublisherRefsRow
		if err := rows.Scan(
			&i.ClientID,
			&i.Kind,
			&i.LastHeartbeatAt,
			&i.StaleAfterS,
			&i.ActiveRefs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRestrictionEvents = `-- name: ListRestrictionEvents :many
SELECT restriction_id, at, op, ansp_version, publication_id, actor
FROM restriction_events
WHERE restriction_id = ANY($1::text[])
ORDER BY restriction_id, at, ansp_version
`

// The events of the heads, oldest first per head.
func (q *Queries) ListRestrictionEvents(ctx context.Context, ids []string) ([]RestrictionEvent, error) {
	rows, err := q.db.Query(ctx, listRestrictionEvents, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RestrictionEvent
	for rows.Next() {
		var i RestrictionEvent
		if err := rows.Scan(
			&i.RestrictionID,
			&i.At,
			&i.Op,
			&i.AnspVersion,
			&i.PublicationID,
			&i.Actor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRestrictions = `-- name: ListRestrictions :many
SELECT id, ansp_ref, ansp_version, uspace_airspace_id, feature_id, state, starts_at, ends_at,
       ended_by, created_at, updated_at, last_publisher_client_id, last_body_sha256
FROM restrictions
WHERE ($1::text IS NULL OR state = $1::text)
  AND ($2::text IS NULL OR uspace_airspace_id = $2::text)
  AND ($3::timestamptz IS NULL
       OR (starts_at <= $3::timestamptz AND ends_at > $3::timestamptz))
ORDER BY starts_at DESC, id DESC
LIMIT $4
`

type ListRestrictionsParams struct {
	State    *string
	Airspace *string
	At       *time.Time
	MaxRows  int32
}

type ListRestrictionsRow struct {
	ID                    string
	AnspRef               string
	AnspVersion           int32
	UspaceAirspaceID      string
	FeatureID             string
	State                 string
	StartsAt              time.Time
	EndsAt                time.Time
	EndedBy               *string
	CreatedAt             time.Time
	UpdatedAt             time.Time
	LastPublisherClientID string
	LastBodySha256        []byte
}

// The heads, newest window first, filtered by state, by U-space airspace
// and by an instant inside the window [starts_at, ends_at).
func (q *Queries) ListRestrictions(ctx context.Context, arg ListRestrictionsParams) ([]ListRestrictionsRow, error) {
	rows, err := q.db.Query(ctx, listRestrictions,
		arg.State,
		arg.Airspace,
		arg.At,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRestrictionsRow
	for rows.Next() {
		var i ListRestrictionsRow
		if err := rows.Scan(
			&i.ID,
			&i.AnspRef,
			&i.AnspVersion,
			&i.UspaceAirspaceID,
			&i.FeatureID,
			&i.State,
			&i.StartsAt,
			&i.EndsAt,
			&i.EndedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastPublisherClientID,
			&i.LastBodySha256,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordJobRun = `-- name: RecordJobRun :exec
INSERT INTO job_runs (name, last_run_at, last_instance, last_count)
VALUES ($1, $2, $3, $4)
ON CONFLICT (name) DO UPDATE
SET last_run_at = EXCLUDED.last_run_at, last_instance = EXCLUDED.last_instance, last_count = EXCLUDED.last_count
`

type RecordJobRunParams struct {
	Name     string
	RanAt    time.Time
	Instance string
	Count    int32
}

func (q *Queries) RecordJobRun(ctx context.Context, arg RecordJobRunParams) error {
	_, err := q.db.Exec(ctx, recordJobRun,
		arg.Name,
		arg.RanAt,
		arg.Instance,
		arg.Count,
	)
	return err
}

const tryJobLock = `-- name: TryJobLock :one
SELECT pg_try_advisory_xact_lock(hashtext('cisp.job.' || $1::text)::bigint) AS locked
`

// Leader election per run: one replica holds the lock until its
// transaction ends; the others skip the run.
func (q *Queries) TryJobLock(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRow(ctx, tryJobLock, name)
	var locked bool
	err := row.Scan(&locked)
	return locked, err
}

const updateRestriction = `-- name: UpdateRestriction :execrows
UPDATE restrictions
SET ansp_version = $1, state = $2, ends_at = $3,
    ended_by = $4, updated_at = $5,
    last_publisher_client_id = $6,
    last_body_sha256 = $7
WHERE id = $8
`

type UpdateRestrictionParams struct {
	AnspVersion           int32
	State                 string
	EndsAt                time.Time
	EndedBy               *string
	UpdatedAt             time.Time
	LastPublisherClientID string
	LastBodySha256        []byte
	ID                    string
}

func (q *Queries) UpdateRestriction(ctx context.Context, arg UpdateRestrictionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateRestriction,
		arg.AnspVersion,
		arg.State,
		arg.EndsAt,
		arg.EndedBy,
		arg.UpdatedAt,
		arg.LastPublisherClientID,
		arg.LastBodySha256,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
