// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: signatures.sql

package relational

import (
	"context"
	"time"
)

const insertSnapshotSignature = `-- name: InsertSnapshotSignature :exec

INSERT INTO snapshot_signatures (dataset, version, kid, signature, body_gz_sha256, signed_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertSnapshotSignatureParams struct {
	Dataset      string
	Version      int64
	Kid          string
	Signature    string
	BodyGzSha256 []byte
	SignedAt     time.Time
}

// Re-signatures of a stored snapshot (retro-audit S5, docs/PLAN.md
// section 15 Q50; migration 0014).
func (q *Queries) InsertSnapshotSignature(ctx context.Context, arg InsertSnapshotSignatureParams) error {
	_, err := q.db.Exec(ctx, insertSnapshotSignature,
		arg.Dataset,
		arg.Version,
		arg.Kid,
		arg.Signature,
		arg.BodyGzSha256,
		arg.SignedAt,
	)
	return err
}
