// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscriptions.sql

package relational

import (
	"context"
	"time"
)

const countClientSubscriptions = `-- name: CountClientSubscriptions :one
SELECT count(*)::bigint FROM subscriptions WHERE client_id = $1 AND status <> 'deleted'
`

// The client's subscriptions that count against its limit (every one
// but the deleted).
func (q *Queries) CountClientSubscriptions(ctx context.Context, clientID string) (int64, error) {
	row := q.db.QueryRow(ctx, countClientSubscriptions, clientID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const expireOpenDeliveries = `-- name: ExpireOpenDeliveries :execrows
UPDATE deliveries SET state = 'expired', next_retry_at = NULL
WHERE subscription_id = $1 AND state IN ('queued', 'failed', 'delivering')
`

// A deleted subscription's queued, failed and stranded deliveries
// expire: a state, never a deletion.
func (q *Queries) ExpireOpenDeliveries(ctx context.Context, subscriptionID string) (int64, error) {
	result, err := q.db.Exec(ctx, expireOpenDeliveries, subscriptionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSubscription = `-- name: GetSubscription :one
SELECT id, client_id, callback_url, datasets, status, created_at, verified_at, suspended_reason,
       consecutive_failures, last_success_at, failing_since,
       (bbox IS NOT NULL)::boolean AS has_bbox,
       COALESCE(ST_XMin(bbox), 0)::float8 AS min_lon, COALESCE(ST_YMin(bbox), 0)::float8 AS min_lat,
       COALESCE(ST_XMax(bbox), 0)::float8 AS max_lon, COALESCE(ST_YMax(bbox), 0)::float8 AS max_lat
FROM subscriptions
WHERE id = $1
`

type GetSubscriptionRow struct {
	ID                  string
	ClientID            string
	CallbackUrl         string
	Datasets            []string
	Status              string
	CreatedAt           time.Time
	VerifiedAt          *time.Time
	SuspendedReason     *string
	ConsecutiveFailures int32
	LastSuccessAt       *time.Time
	FailingSince        *time.Time
	HasBbox             bool
	MinLon              float64
	MinLat              float64
	MaxLon              float64
	MaxLat              float64
}

func (q *Queries) GetSubscription(ctx context.Context, id string) (GetSubscriptionRow, error) {
	row := q.db.QueryRow(ctx, getSubscription, id)
	var i GetSubscriptionRow
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.CallbackUrl,
		&i.Datasets,
		&i.Status,
		&i.CreatedAt,
		&i.VerifiedAt,
		&i.SuspendedReason,
		&i.ConsecutiveFailures,
		&i.LastSuccessAt,
		&i.FailingSince,
		&i.HasBbox,
		&i.MinLon,
		&i.MinLat,
		&i.MaxLon,
		&i.MaxLat,
	)
	return i, err
}

const getSubscriptionDelivery = `-- name: GetSubscriptionDelivery :one
SELECT d.id, d.subscription_id, d.change_id, d.state, d.attempts, d.first_attempt_at, d.last_attempt_at,
       d.next_retry_at, d.delivered_at, d.last_status_code, d.last_error, d.created_at,
       COALESCE(c.reason, 'subscription_test')::text AS reason
FROM deliveries d
LEFT JOIN changes c ON c.id = d.change_id
WHERE d.id = $1 AND d.subscription_id = $2
`

type GetSubscriptionDeliveryParams struct {
	ID             string
	SubscriptionID string
}

type GetSubscriptionDeliveryRow struct {
	ID             string
	SubscriptionID string
	ChangeID       *int64
	State          string
	Attempts       int32
	FirstAttemptAt *time.Time
	LastAttemptAt  *time.Time
	NextRetryAt    *time.Time
	DeliveredAt    *time.Time
	LastStatusCode *int32
	LastError      *string
	CreatedAt      time.Time
	Reason         string
}

func (q *Queries) GetSubscriptionDelivery(ctx context.Context, arg GetSubscriptionDeliveryParams) (GetSubscriptionDeliveryRow, error) {
	row := q.db.QueryRow(ctx, getSubscriptionDelivery, arg.ID, arg.SubscriptionID)
	var i GetSubscriptionDeliveryRow
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.ChangeID,
		&i.State,
		&i.Attempts,
		&i.FirstAttemptAt,
		&i.LastAttemptAt,
		&i.NextRetryAt,
		&i.DeliveredAt,
		&i.LastStatusCode,
		&i.LastError,
		&i.CreatedAt,
		&i.Reason,
	)
	return i, err
}

const insertPingDelivery = `-- name: InsertPingDelivery :exec
INSERT INTO deliveries (id, subscription_id, change_id, state, next_retry_at, created_at)
VALUES ($1, $2, NULL, 'queued', $3::timestamptz, $3::timestamptz)
`

type InsertPingDeliveryParams struct {
	ID             string
	SubscriptionID string
	CreatedAt      time.Time
}

// The verification ping of a subscription: a delivery of no change,
// due now.
func (q *Queries) InsertPingDelivery(ctx context.Context, arg InsertPingDeliveryParams) error {
	_, err := q.db.Exec(ctx, insertPingDelivery, arg.ID, arg.SubscriptionID, arg.CreatedAt)
	return err
}

const insertSubscription = `-- name: InsertSubscription :exec
INSERT INTO subscriptions (id, client_id, callback_url, datasets, bbox, status, created_at)
VALUES (
    $1, $2, $3, $4::text[],
    CASE WHEN $5::boolean
         THEN ST_MakeEnvelope($6::float8, $7::float8,
                              $8::float8, $9::float8, 4326)
    END,
    $10, $11
)
`

type InsertSubscriptionParams struct {
	ID          string
	ClientID    string
	CallbackUrl string
	Datasets    []string
	HasBbox     bool
	MinLon      float64
	MinLat      float64
	MaxLon      float64
	MaxLat      float64
	Status      string
	CreatedAt   time.Time
}

func (q *Queries) InsertSubscription(ctx context.Context, arg InsertSubscriptionParams) error {
	_, err := q.db.Exec(ctx, insertSubscription,
		arg.ID,
		arg.ClientID,
		arg.CallbackUrl,
		arg.Datasets,
		arg.HasBbox,
		arg.MinLon,
		arg.MinLat,
		arg.MaxLon,
		arg.MaxLat,
		arg.Status,
		arg.CreatedAt,
	)
	return err
}

const latestPingDelivery = `-- name: LatestPingDelivery :one
SELECT id, subscription_id, change_id, state, attempts, first_attempt_at, last_attempt_at, next_retry_at,
       delivered_at, last_status_code, last_error, created_at
FROM deliveries
WHERE subscription_id = $1 AND change_id IS NULL
ORDER BY created_at DESC, id DESC
LIMIT 1
`

func (q *Queries) LatestPingDelivery(ctx context.Context, subscriptionID string) (Delivery, error) {
	row := q.db.QueryRow(ctx, latestPingDelivery, subscriptionID)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.ChangeID,
		&i.State,
		&i.Attempts,
		&i.FirstAttemptAt,
		&i.LastAttemptAt,
		&i.NextRetryAt,
		&i.DeliveredAt,
		&i.LastStatusCode,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const listClientSubscriptions = `-- name: ListClientSubscriptions :many
SELECT id, client_id, callback_url, datasets, status, created_at, verified_at, suspended_reason,
       consecutive_failures, last_success_at, failing_since,
       (bbox IS NOT NULL)::boolean AS has_bbox,
       COALESCE(ST_XMin(bbox), 0)::float8 AS min_lon, COALESCE(ST_YMin(bbox), 0)::float8 AS min_lat,
       COALESCE(ST_XMax(bbox), 0)::float8 AS max_lon, COALESCE(ST_YMax(bbox), 0)::float8 AS max_lat
FROM subscriptions
WHERE client_id = $1 AND status <> 'deleted'
ORDER BY created_at, id
LIMIT $2
`

type ListClientSubscriptionsParams struct {
	ClientID string
	MaxRows  int32
}

type ListClientSubscriptionsRow struct {
	ID                  string
	ClientID            string
	CallbackUrl         string
	Datasets            []string
	Status              string
	CreatedAt           time.Time
	VerifiedAt          *time.Time
	SuspendedReason     *string
	ConsecutiveFailures int32
	LastSuccessAt       *time.Time
	FailingSince        *time.Time
	HasBbox             bool
	MinLon              float64
	MinLat              float64
	MaxLon              float64
	MaxLat              float64
}

// The client's subscriptions but the deleted, oldest first.
func (q *Queries) ListClientSubscriptions(ctx context.Context, arg ListClientSubscriptionsParams) ([]ListClientSubscriptionsRow, error) {
	rows, err := q.db.Query(ctx, listClientSubscriptions, arg.ClientID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClientSubscriptionsRow
	for rows.Next() {
		var i ListClientSubscriptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.CallbackUrl,
			&i.Datasets,
			&i.Status,
			&i.CreatedAt,
			&i.VerifiedAt,
			&i.SuspendedReason,
			&i.ConsecutiveFailures,
			&i.LastSuccessAt,
			&i.FailingSince,
			&i.HasBbox,
			&i.MinLon,
			&i.MinLat,
			&i.MaxLon,
			&i.MaxLat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionDeliveries = `-- name: ListSubscriptionDeliveries :many
SELECT d.id, d.subscription_id, d.change_id, d.state, d.attempts, d.first_attempt_at, d.last_attempt_at,
       d.next_retry_at, d.delivered_at, d.last_status_code, d.last_error, d.created_at,
       COALESCE(c.reason, 'subscription_test')::text AS reason
FROM deliveries d
LEFT JOIN changes c ON c.id = d.change_id
WHERE d.subscription_id = $1 AND d.created_at >= $2
ORDER BY d.created_at DESC, d.id DESC
LIMIT $3
`

type ListSubscriptionDeliveriesParams struct {
	SubscriptionID string
	Since          time.Time
	MaxRows        int32
}

type ListSubscriptionDeliveriesRow struct {
	ID             string
	SubscriptionID string
	ChangeID       *int64
	State          string
	Attempts       int32
	FirstAttemptAt *time.Time
	LastAttemptAt  *time.Time
	NextRetryAt    *time.Time
	DeliveredAt    *time.Time
	LastStatusCode *int32
	LastError      *string
	CreatedAt      time.Time
	Reason         string
}

// A subscription's deliveries queued at or after since, newest first,
// with the reason of their change (subscription_test for a ping).
func (q *Queries) ListSubscriptionDeliveries(ctx context.Context, arg ListSubscriptionDeliveriesParams) ([]ListSubscriptionDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, listSubscriptionDeliveries, arg.SubscriptionID, arg.Since, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubscriptionDeliveriesRow
	for rows.Next() {
		var i ListSubscriptionDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.SubscriptionID,
			&i.ChangeID,
			&i.State,
			&i.Attempts,
			&i.FirstAttemptAt,
			&i.LastAttemptAt,
			&i.NextRetryAt,
			&i.DeliveredAt,
			&i.LastStatusCode,
			&i.LastError,
			&i.CreatedAt,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockClientSubscriptions = `-- name: LockClientSubscriptions :exec

SELECT pg_advisory_xact_lock(hashtext('cisp.subscriptions.' || $1::text)::bigint)
`

// WP-6: the subscriptions and their deliveries as the api reads and
// writes them (docs/PLAN.md section 6.5). The bounding box is stored as
// a polygon (SRID 4326) and read back as its four edges.
// Serialises the creates of one client, so two at once cannot both pass
// the limit.
func (q *Queries) LockClientSubscriptions(ctx context.Context, clientID string) error {
	_, err := q.db.Exec(ctx, lockClientSubscriptions, clientID)
	return err
}

const markSubscriptionDeleted = `-- name: MarkSubscriptionDeleted :exec
UPDATE subscriptions SET status = 'deleted' WHERE id = $1
`

func (q *Queries) MarkSubscriptionDeleted(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markSubscriptionDeleted, id)
	return err
}

const requeueDelivery = `-- name: RequeueDelivery :execrows
UPDATE deliveries SET state = 'queued', next_retry_at = $1::timestamptz
WHERE id = $2 AND subscription_id = $3 AND state <> 'delivering'
`

type RequeueDeliveryParams struct {
	Now            time.Time
	ID             string
	SubscriptionID string
}

// A retry: due now, whatever it was, unless an attempt is in flight.
func (q *Queries) RequeueDelivery(ctx context.Context, arg RequeueDeliveryParams) (int64, error) {
	result, err := q.db.Exec(ctx, requeueDelivery, arg.Now, arg.ID, arg.SubscriptionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateSubscription = `-- name: UpdateSubscription :exec
UPDATE subscriptions SET
    callback_url = $1,
    datasets = $2::text[],
    bbox = CASE WHEN $3::boolean
                THEN ST_MakeEnvelope($4::float8, $5::float8,
                                     $6::float8, $7::float8, 4326)
           END,
    status = $8,
    suspended_reason = $9,
    consecutive_failures = $10,
    failing_since = $11
WHERE id = $12
`

type UpdateSubscriptionParams struct {
	CallbackUrl         string
	Datasets            []string
	HasBbox             bool
	MinLon              float64
	MinLat              float64
	MaxLon              float64
	MaxLat              float64
	Status              string
	SuspendedReason     *string
	ConsecutiveFailures int32
	FailingSince        *time.Time
	ID                  string
}

// A PATCH: the callback, datasets and box as given; status and the
// failure run as the handler decided (a re-verification resets them).
func (q *Queries) UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) error {
	_, err := q.db.Exec(ctx, updateSubscription,
		arg.CallbackUrl,
		arg.Datasets,
		arg.HasBbox,
		arg.MinLon,
		arg.MinLat,
		arg.MaxLon,
		arg.MaxLat,
		arg.Status,
		arg.SuspendedReason,
		arg.ConsecutiveFailures,
		arg.FailingSince,
		arg.ID,
	)
	return err
}
